# -*- coding: utf-8 -*-
"""Build standalone index.html for the Fruit Flies EU (Detailed) dashboard.

THREE-tab standalone, Polish UI, NO product segment (pack-size structure instead):
  Tab 1 · Rynek           - cross-market topline (generated by _build_rynek.py)
  Tab 2 · Struktura rynku - pack-size x brand market structure per country
                            (generated by _build_structure.py), modelled on the
                            fruit-fly-trap-DE dashboard's Market Structure tab.
  Tab 3 · Recenzje (VOC)  - UK-only Voice-of-Customer (generated by _build_voc.py),
                            reuses the u-reviews-voc template + provecta's Polish
                            transform. Only UK has scraped reviews.

Markets: FR / IT / ES / UK. All EUR (UK GBP converted upstream in _consolidate.py).
12M projection uses the German seasonality multiplier (~x7.90, July export).

Pipeline:
  1. Run _build_rynek.py     -> _rynek_topline.html   (tab 1 body)
  2. Run _build_structure.py -> _structure.html       (tab 2 fragment)
  3. Run _build_voc.py       -> _voc.html             (tab 3 fragment, UK only)
  4. Assemble the ad-* shell (header + 3-tab bar + 3 panels) -> index.html.
     Tabs 2 & 3 render lazily the first time opened (canvas must be visible to
     size correctly) via window.__structRender() / window.__vocRender().

Run (Windows):
    python _build_standalone.py
"""
import os, re, sys, subprocess

try:
    sys.stdout.reconfigure(encoding='utf-8')
except Exception:
    pass

BASE = os.path.dirname(os.path.abspath(__file__))
RYNEK_HTML = os.path.join(BASE, '_rynek_topline.html')
STRUCT_HTML = os.path.join(BASE, '_structure.html')
VOC_HTML = os.path.join(BASE, '_voc.html')
VOC_STICKY_HTML = os.path.join(BASE, '_voc_sticky.html')

# ── Identity ────────────────────────────────────────────────────────────────
PRODUCT_TITLE = 'Fruit Flies EU - Detailed (FR, IT, ES, UK)'
DASHBOARD_H2  = 'Fruit Flies EU - Analiza szczegółowa'
DASHBOARD_SUB = 'Rynki: Francja · Włochy · Hiszpania · Wielka Brytania · Dane: Helium 10 X-Ray (projekcja 30d z sezonowością rynku DE, EUR)'

XRAY_LINKS = {'FR': '#', 'IT': '#', 'ES': '#', 'UK': '#'}
FLAG = {'FR': '\U0001F1EB\U0001F1F7', 'IT': '\U0001F1EE\U0001F1F9', 'ES': '\U0001F1EA\U0001F1F8', 'UK': '\U0001F1EC\U0001F1E7'}

# ── 1-2. Regenerate both tab sources ────────────────────────────────────────
print('Running _build_seasonality.py ...')
subprocess.run([sys.executable, os.path.join(BASE, '_build_seasonality.py')], check=True)
print('Running _build_rynek.py ...')
subprocess.run([sys.executable, os.path.join(BASE, '_build_rynek.py')], check=True)
print('Running _build_structure.py ...')
subprocess.run([sys.executable, os.path.join(BASE, '_build_structure.py')], check=True)
print('Running _build_voc.py ...')
subprocess.run([sys.executable, os.path.join(BASE, '_build_voc.py')], check=True)
print('Running _build_voc_sticky.py ...')
subprocess.run([sys.executable, os.path.join(BASE, '_build_voc_sticky.py')], check=True)

rynek = open(RYNEK_HTML, encoding='utf-8').read()
m_style = re.search(r'<style>(.*?)</style>', rynek, re.S)
m_body  = re.search(r'<body>(.*?)</body>', rynek, re.S)
if not m_style or not m_body:
    raise SystemExit('could not extract <style>/<body> from _rynek_topline.html')
topline_css  = m_style.group(1)
topline_body = re.sub(r'<header>.*?</header>', '', m_body.group(1), flags=re.S)

structure_body = open(STRUCT_HTML, encoding='utf-8').read()
voc_body = open(VOC_HTML, encoding='utf-8').read()
voc_sticky_body = open(VOC_STICKY_HTML, encoding='utf-8').read()

# ── X-Ray buttons (only real links) ─────────────────────────────────────────
xray_buttons = ''
for code, href in XRAY_LINKS.items():
    if href and href != '#':
        xray_buttons += (
            f'<a class="ad-xray-btn" href="{href}" target="_blank" rel="noopener">'
            f'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">'
            f'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>'
            f'<polyline points="14 2 14 8 20 8"/></svg>{FLAG.get(code, "")} {code} X-Ray</a>'
        )

# ── Shell CSS (shared "ad-*" chrome + "ms2-*" structure tab) ────────────────
SHELL_CSS = r'''
  *,*::before,*::after { box-sizing: border-box; }
  body { margin: 0; font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif; background: #f1f5f9; color: #0f172a; font-size: 14px; }
  .ad-header { background: #0f2942; color: #fff; padding: 16px 32px; display: flex; justify-content: space-between; align-items: center; gap: 24px; flex-wrap: wrap; }
  .ad-header .ad-hd-titles { flex: 1; min-width: 0; }
  .ad-header h1 { margin: 0; font-size: 1.3rem; font-weight: 700; color: #fff; letter-spacing: .01em; }
  .ad-header .ad-hd-sub { display: block; margin-top: 4px; font-size: .76rem; color: #cbd5e1; }
  .ad-xray-btns { display: flex; gap: 8px; flex-wrap: wrap; }
  .ad-xray-btn { background: #16a34a; color: #fff; padding: 8px 14px; border-radius: 6px; font-size: .76rem; font-weight: 600; text-decoration: none; white-space: nowrap; display: inline-flex; align-items: center; gap: 6px; box-shadow: 0 1px 3px rgba(0,0,0,.2); transition: background .15s; }
  .ad-xray-btn:hover { background: #15803d; }
  .ad-xray-btn svg { width: 14px; height: 14px; }
  .ad-tabs { display: flex; gap: 4px; border-bottom: 2px solid #e2e8f0; flex-wrap: wrap; position: sticky; top: 0; z-index: 40; background: #f1f5f9; padding: 12px 32px 0; }
  .ad-tab { padding: 10px 18px; background: transparent; border: none; cursor: pointer; font-size: .9rem; font-weight: 600; color: #64748b; border-bottom: 3px solid transparent; margin-bottom: -2px; transition: color .15s, border-color .15s; white-space: nowrap; }
  .ad-tab:hover { color: #0f172a; }
  .ad-tab.active { color: #0f2942; border-bottom-color: #0f2942; }
  .ad-panel { display: none; }
  .ad-panel.active { display: block; }

  /* ── Struktura rynku (Tab 2) ── */
  .ms2-wrap { max-width: 1200px; margin: 0 auto; padding: 20px 24px 40px; }
  .ms2-pillrow { display: flex; gap: 8px; flex-wrap: wrap; align-items: center; margin-bottom: 18px; }
  .ms2-pilllabel { font-size: .72rem; font-weight: 700; color: #64748b; text-transform: uppercase; letter-spacing: .04em; margin-right: 4px; }
  .ms2-pill { padding: 7px 15px; border: 2px solid #cbd5e1; background: #fff; border-radius: 20px; cursor: pointer; font-size: .78rem; font-weight: 600; color: #475569; transition: all .15s; }
  .ms2-pill:hover { border-color: #94a3b8; color: #1e293b; }
  .ms2-pill.active { background: #0f2942; border-color: #0f2942; color: #fff; }
  .ms2-kpis { display: grid; grid-template-columns: repeat(6,1fr); gap: 12px; margin-bottom: 22px; }
  @media (max-width: 900px) { .ms2-kpis { grid-template-columns: repeat(3,1fr); } }
  .ms2-kpi { background: #fff; border-radius: 8px; padding: 12px 14px; box-shadow: 0 1px 3px rgba(0,0,0,.07); }
  .ms2-kpi-v { font-size: 1.15rem; font-weight: 700; color: #0f2942; line-height: 1.15; }
  .ms2-kpi-l { font-size: .64rem; color: #64748b; margin-top: 5px; text-transform: uppercase; letter-spacing: .04em; }
  .ms2-card { background: #fff; border-radius: 8px; padding: 16px 18px; box-shadow: 0 1px 3px rgba(0,0,0,.07); margin-bottom: 18px; }
  .ms2-card h3 { font-size: .82rem; font-weight: 600; color: #475569; margin: 0 0 14px; }
  .ms2-cw { position: relative; }
  .ms2-row2 { display: grid; grid-template-columns: 1fr 1fr; gap: 18px; }
  .ms2-row3 { display: grid; grid-template-columns: repeat(3,1fr); gap: 18px; margin-bottom: 18px; }
  .ms2-row2 .ms2-card, .ms2-row3 .ms2-card { margin-bottom: 0; }
  @media (max-width: 860px) { .ms2-row2, .ms2-row3 { grid-template-columns: 1fr; } }
  .ms2-tblwrap { overflow-x: auto; }
  .ms2-tbl { width: 100%; border-collapse: collapse; font-size: .78rem; }
  .ms2-tbl th { background: #f8fafc; text-align: left; padding: 7px 9px; font-weight: 600; color: #475569; font-size: .68rem; text-transform: uppercase; letter-spacing: .03em; border-bottom: 2px solid #e2e8f0; cursor: pointer; user-select: none; white-space: nowrap; }
  .ms2-tbl th.num { text-align: right; }
  .ms2-tbl th:hover { background: #f1f5f9; }
  .ms2-tbl th.sa::after { content: ' ▲'; color: #0f2942; }
  .ms2-tbl th.sd::after { content: ' ▼'; color: #0f2942; }
  .ms2-tbl td { padding: 7px 9px; border-bottom: 1px solid #f1f5f9; }
  .ms2-tbl td.num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
  .ms2-tbl tr:hover td { background: #f8fafc; }
  .ms2-title { display: inline-block; max-width: 340px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; vertical-align: bottom; }
  .ms2-asin { background: #dbeafe; color: #1d4ed8; padding: 2px 7px; border-radius: 3px; font-size: .7rem; font-family: ui-monospace,Menlo,Consolas,monospace; font-weight: 600; text-decoration: none; }
  .ms2-asin:hover { background: #bfdbfe; text-decoration: underline; }
  .ms2-note { font-size: .68rem; color: #64748b; margin-top: 10px; padding: 8px 11px; background: #f8fafc; border-radius: 6px; border-left: 2px solid #cbd5e1; line-height: 1.5; }
'''

HTML = r'''<!DOCTYPE html>
<html lang="pl">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{TITLE}}</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.2.0/dist/chartjs-plugin-datalabels.min.js"></script>
<style>/* (a) shell */
{{SHELL_CSS}}
</style>
<style>/* (b) topline (verbatim) */
{{TOPLINE_CSS}}
</style>
</head>
<body>

<header class="ad-header">
  <div class="ad-hd-titles">
    <h1>{{DASHBOARD_H2}}</h1>
    <span class="ad-hd-sub">{{DASHBOARD_SUB}}</span>
  </div>
  <div class="ad-xray-btns">{{XRAY_BUTTONS}}</div>
</header>

<div class="ad-tabs">
  <button class="ad-tab active" data-tab="market">Rynek</button>
  <button class="ad-tab" data-tab="structure">Struktura rynku</button>
  <button class="ad-tab" data-tab="voc">Recenzje (VOC)</button>
  <button class="ad-tab" data-tab="voc-sticky">VOC - sticky traps</button>
</div>

<div class="ad-panel active" id="panel-market">
{{TOPLINE_BODY}}
</div>

<div class="ad-panel" id="panel-structure">
{{STRUCTURE_BODY}}
</div>

<div class="ad-panel" id="panel-voc">
{{VOC_BODY}}
</div>

<div class="ad-panel" id="panel-voc-sticky">
{{VOC_STICKY_BODY}}
</div>

<script>
(function(){
  var structRendered = false, vocRendered = false, vocStickyRendered = false;
  document.querySelectorAll('.ad-tab').forEach(function(t){
    t.addEventListener('click', function(){
      var tab = t.dataset.tab;
      document.querySelectorAll('.ad-tab').forEach(function(x){ x.classList.toggle('active', x === t); });
      document.getElementById('panel-market').classList.toggle('active', tab === 'market');
      document.getElementById('panel-structure').classList.toggle('active', tab === 'structure');
      document.getElementById('panel-voc').classList.toggle('active', tab === 'voc');
      document.getElementById('panel-voc-sticky').classList.toggle('active', tab === 'voc-sticky');
      if (tab === 'structure' && !structRendered && window.__structRender) {
        structRendered = true;
        window.__structRender();
      }
      if (tab === 'voc' && !vocRendered && window.__vocRender) {
        vocRendered = true;
        window.__vocRender();
      }
      if (tab === 'voc-sticky' && !vocStickyRendered && window.__vocStickyRender) {
        vocStickyRendered = true;
        window.__vocStickyRender();
      }
    });
  });
})();
</script>

</body>
</html>
'''

html_out = (HTML
    .replace('{{TITLE}}', PRODUCT_TITLE)
    .replace('{{SHELL_CSS}}', SHELL_CSS)
    .replace('{{TOPLINE_CSS}}', topline_css)
    .replace('{{DASHBOARD_H2}}', DASHBOARD_H2)
    .replace('{{DASHBOARD_SUB}}', DASHBOARD_SUB)
    .replace('{{XRAY_BUTTONS}}', xray_buttons)
    .replace('{{TOPLINE_BODY}}', topline_body)
    .replace('{{STRUCTURE_BODY}}', structure_body)
    .replace('{{VOC_BODY}}', voc_body)
    .replace('{{VOC_STICKY_BODY}}', voc_sticky_body)
)

# Style guard: no em/en dashes in shell text (fragments already sanitized).
html_out = html_out.replace('—', '-').replace('–', '-')

out_path = os.path.join(BASE, 'index.html')
with open(out_path, 'w', encoding='utf-8') as f:
    f.write(html_out)

print(f'\nindex.html: {os.path.getsize(out_path):,} bytes  ->  {out_path}')
