"""Translate analytical labels in voc.json files (DE/FR -> EN).

Quotes and review text stay in source language (real customer voice).
Only labels, reasons, bullets, findings, implications, summaries, dimension
names, and theme filters get translated.

Run: py _translate_voc.py
"""
import json, os, sys
sys.stdout.reconfigure(encoding='utf-8')

BASE = os.path.dirname(os.path.abspath(__file__))

T = {
    # ── DE Lure ──────────────────────────────────────────────────────────────
    "Kernzielgruppe sind <b>Garten- und Terrassennutzer</b> sowie <b>Familien mit Kindern</b>, die Wespen am Esstisch und während der <b>Grillsaison</b> abfangen wollen — ohne Strom und ohne Gift. Sekundär: <b>Allergiker</b> und Käufer mit <b>Wespennest in der Nähe</b>, oft präventiv im Frühjahr.": "Core audience: <b>garden and patio users</b> plus <b>families with children</b> who want to keep wasps off the dinner table during <b>BBQ season</b>, without electricity or chemicals. Secondary: <b>allergy sufferers</b> and buyers with a <b>nearby wasp nest</b>, often deploying pre-emptively in spring.",
    "Bei <b>329</b> Reviews dominiert das Thema <b>Köder-Selektivität</b> — viele Fallen ziehen auch Bienen und Hummeln an. Sekundär kritisch: <b>Köder trocknet schnell aus</b> und <b>Wirkung gegen Konkurrenz-Nahrungsquellen</b>. Positiv hervorgehoben werden <b>sichtbarer Erfolg</b> (volle Falle), <b>einfache Handhabung</b> und <b>Sicherheit ohne Strom/Gift</b>.": "Across <b>329</b> reviews, <b>bait selectivity</b> dominates — many traps also attract bees and bumblebees. Secondary pain: <b>bait dries out quickly</b> and <b>loses out to competing food sources nearby</b>. Top praise: <b>visible success</b> (full trap), <b>easy handling</b>, and <b>safety without electricity or chemicals</b>.",
    "Hausbesitzer": "Homeowners",
    "Garten/Terrassennutzer": "Garden/patio users",
    "Eltern mit Kindern": "Parents with kids",
    "Allergiker": "Allergy sufferers",
    "Gastronomen": "Restaurant/cafe owners",
    "Tierhalter": "Pet owners",
    "Imker": "Beekeepers",
    "Frühlingsstart": "Spring start",
    "Sommer-Peak": "Summer peak",
    "Bei Wespennest entdeckt": "After spotting nest",
    "BBQ/Grillsaison": "BBQ season",
    "Vor der Saison": "Pre-emptive (before season)",
    "Terrasse/Garten": "Garden/patio",
    "Balkon": "Balcony",
    "Obstbäume": "Fruit trees",
    "Esstisch im Freien": "Outdoor dining",
    "Hauseingang": "Near doors/windows",
    "Dachüberstand": "Eaves/overhang",
    "Hängefalle mit Köder": "Hanging trap with bait",
    "Köder-Sachet": "Bait sachet",
    "Mehrweg-Glockenfalle": "Reusable bell trap",
    "Flaschenfalle": "Bottle trap",
    "Klebefalle": "Sticky trap",
    "Fängt keine Wespen / wirkungslos": "Doesn't catch wasps / ineffective",
    "Häufigster Frust: die Falle hängt, aber Wespen umfliegen sie und gehen lieber direkt aufs Essen.": "Top frustration: the trap is hanging there, but wasps fly around it and head straight for the food instead.",
    "14 von 134 negativen Bewertungen (10.4%) berichten von Wirkungslosigkeit": "14 of 134 negative reviews (10.4%) report ineffectiveness",
    "Wespen umfliegen die Falle und bleiben am Essen — Hauptbeschwerde": "Wasps fly around the trap and stay on the food — top complaint",
    "Konkurrenz durch nahe Nahrungsquellen (Obst, Grill) wird unterschätzt": "Competing food sources nearby (fruit, BBQ) are underestimated",
    "Erwartung 'fängt sofort alle Wespen' wird selten erfüllt": "Expectation 'catches all wasps instantly' is rarely met",
    "Verarbeitung / Reinigung": "Build quality / cleaning",
    "Plastik bricht, Falle ist undicht, Reinigung der vollen Falle ist eklig und umständlich.": "Plastic breaks, trap leaks, emptying a full trap is gross and awkward.",
    "0.7% (1) mit Verarbeitungs- oder Reinigungsproblemen": "0.7% (1) with build or cleaning issues",
    "Plastikteile brechen beim Öffnen oder Reinigen": "Plastic parts break when opening or cleaning",
    "Falle ist undicht — Lockstoff läuft aus": "Trap leaks — bait drips out",
    "Volle Falle leeren ist eklig und umständlich": "Emptying a full trap is gross and awkward",
    "Fängt sehr viele Wespen": "Catches lots of wasps",
    "Falle voll mit Wespen binnen Stunden — sichtbarer Erfolg überzeugt sofort.": "Trap full of wasps within hours — visible success is instantly convincing.",
    "8 von 159 positiven Bewertungen (5.0%) loben die Wirksamkeit": "8 of 159 positive reviews (5.0%) praise the effectiveness",
    "Voll mit Wespen binnen Stunden — sichtbarer Beweis": "Full of wasps within hours — visible proof",
    "Massive Reduktion am Esstisch / im Garten": "Major reduction at the dinner table / in the garden",
    "Endlich wieder ungestört draußen sitzen": "Finally able to sit outside undisturbed again",
    "Langlebig & wiederverwendbar": "Durable & reusable",
    "Glocken-/Mehrwegfallen halten mehrere Saisons — Plastik bleibt stabil.": "Bell-/reusable traps last multiple seasons — plastic stays sturdy.",
    "1 (0.6%) berichten von langer Lebensdauer": "1 (0.6%) report long lifespan",
    "Glocken-/Mehrwegfallen halten mehrere Saisons": "Bell-/reusable traps last multiple seasons",
    "Plastik bleibt stabil und bricht nicht": "Plastic stays sturdy and doesn't break",
    "Wiederverwendbarkeit ist nachhaltiger als Wegwerf-Beutel": "Reusable is more sustainable than disposable bags",
    "Perfekt für Garten/Terrasse": "Perfect for garden/patio",
    "Klassischer Outdoor-Einsatz — Garten oder Terrasse wird wieder nutzbar.": "Classic outdoor use — the garden or patio becomes usable again.",
    "0.6% (1) nutzen sie im Garten/auf der Terrasse": "0.6% (1) use it in the garden/on the patio",
    "Klassischer Outdoor-Einsatz dominiert": "Classic outdoor use dominates",
    "Garten/Terrasse wird wieder nutzbar": "Garden/patio becomes usable again",
    "Auch am Pool oder im Schrebergarten": "Also at the pool or in the allotment",
    "Süßer Universal-Lockstoff zieht alles mit Süßzahn an — Bienen, Hummeln und Fliegen sterben mit. Top-Treiber für 1-Stern-Reviews bei tier- und naturliebenden Kunden.": "Sweet universal bait attracts everything with a sweet tooth — bees, bumblebees and flies die alongside. Top driver of 1-star reviews from animal-loving and eco-conscious customers.",
    "Selektiver Lockstoff (proteinhaltig im Spätsommer, Pheromon-basiert) als USP entwickeln und kommunizieren. 'Bienenfreundlich' ist ein verkaufendes Bullet, nicht nur ein Compliance-Detail.": "Develop and communicate a selective bait (protein-based in late summer, pheromone-based) as a USP. 'Bee-friendly' is a selling bullet, not just a compliance detail.",
    "Lockstoff trocknet in der Sommerhitze in 3–5 Tagen aus — Käufer fühlen sich gezwungen, ständig nachzukaufen oder die Falle wirkt nicht mehr.": "Bait dries out in 3–5 days in summer heat — buyers feel forced to keep buying refills or the trap stops working.",
    "Verdunstungsschutz (Deckel, Reservoir, Kapsel) als Designmerkmal. Nachfüll-Sachets im Lieferumfang (mindestens 3 Stück) erhöhen Erstkauf-Zufriedenheit deutlich.": "Evaporation protection (lid, reservoir, capsule) as a design feature. Including refill sachets (at least 3) significantly raises first-purchase satisfaction.",
    "Wespen bevorzugen den Grill, das Eis, das Fallobst — die Falle verliert den Lockstoff-Wettkampf gegen reale Nahrung in 2 m Entfernung.": "Wasps prefer the BBQ, the ice cream, the fallen fruit — the trap loses the bait competition against real food 2m away.",
    "Listing muss 'mindestens 3–5 m vom Esstisch entfernt aufstellen' als Hauptanwendungs-Hinweis kommunizieren. Edukation > Produktversprechen. A+-Modul mit Aufstell-Schema.": "Listing must communicate 'place at least 3–5m from the dining table' as the primary usage instruction. Education > product promise. A+ module with placement diagram.",
    "Volle Falle mit ertrunkenen Wespen leeren ist eklig und ein Hauptkritikpunkt bei wiederverwendbaren Modellen — Einweg-Modelle umgehen das, sind aber ökologisch problematisch.": "Emptying a full trap of drowned wasps is gross and a top complaint for reusable models — disposable models avoid it but are ecologically problematic.",
    "'No-Touch'-Entleerung (Bodenklappe, Einsatz herausziehen) ist klares Differenzierungsmerkmal. Im Hauptbild oder Video zeigen.": "'No-touch' emptying (bottom flap, pull-out insert) is a clear differentiator. Show it in the hero image or video.",
    "Süßlich-fauliger Lockstoff-Geruch stört auch Menschen — besonders am Esstisch, wo die Falle ja eigentlich Gäste schützen soll.": "Sweet-rotten bait smell bothers people too — especially at the dining table, where the trap is supposed to protect guests.",
    "Geruchs-neutrale oder pheromon-basierte Lockstoffe als Premium-Variante. Aufstellungs-Empfehlung 'außerhalb der Sitzplätze' verstärken.": "Odour-neutral or pheromone-based baits as a premium variant. Reinforce the 'place away from seating' instruction.",
    "Falle weht bei Wind um, Plastik vergilbt und wird nach einer Saison brüchig — Lebensdauer-Versprechen wird oft nicht eingehalten.": "Trap blows over in wind, plastic yellows and turns brittle after one season — durability promise often not kept.",
    "UV-stabilisiertes Material plus Befestigungs-Set (Karabiner, Stahlhaken) im Lieferumfang. Klare 2-Saisons-Garantie würde die Negativ-Reviews stark reduzieren.": "UV-stabilised material plus mounting kit (carabiner, steel hook) in the box. A clear 2-season warranty would sharply cut negative reviews.",
    "SWISSINNO dominiert das Lure-Segment in DE — Käufer kaufen explizit wegen Schweizer Qualitätsversprechen, auch zum höheren Preis.": "SWISSINNO dominates the DE Lure segment — buyers explicitly choose it for the Swiss quality promise, even at a higher price.",
    "Marken-Geschichte (Schweizer Hersteller, Forschung, Naturschutz) prominent im A+-Modul. Privat-Label-Wettbewerber müssen entweder klar unterbieten oder eine starke alternative Story aufbauen.": "Brand story (Swiss manufacturer, R&D, conservation) prominent in the A+ module. Private-label competitors must either undercut clearly or build a strong alternative narrative.",
    "'Endlich wieder ungestört grillen' ist der emotionalste Trigger in positiven Reviews — stärker als allgemeines 'Garten'.": "'Finally undisturbed BBQs again' is the most emotional trigger in positive reviews — stronger than generic 'garden'.",
    "Hauptbild und Hero-Video sollten BBQ-Szene zeigen, nicht generischen Garten. Bundle-Angebot mit Grill-Saison-Start (April/Mai).": "Hero image and video should show a BBQ scene, not a generic garden. Bundle offer at BBQ-season start (April/May).",
    "'Voll mit Wespen binnen Stunden' ist der wichtigste Wow-Effekt — Käufer fotografieren volle Fallen und teilen es in Reviews.": "'Full of wasps within hours' is the biggest wow moment — buyers photograph full traps and share them in reviews.",
    "UGC-Kampagne 'Zeig deine volle Falle' aktiv pushen. Hero-Image im Listing sollte real volle Falle zeigen, kein Stock-Foto.": "Actively push a UGC campaign 'show your full trap'. Listing hero image should show a real full trap, not a stock photo.",
    "Käufer mögen, wenn die Falle nicht industriell aussieht — Glocken-Form und unauffällige Farben gewinnen gegen knallrote Plastikbeutel.": "Buyers prefer traps that don't look industrial — bell shapes and discreet colours win over bright-red plastic bags.",
    "Premium-Variante in Glas, Keramik oder Holzoptik. Mehrfarb-Auswahl (Garten-Grün, Anthrazit, Weiß) als Variante.": "Premium variant in glass, ceramic or wood-look finish. Colour options (garden green, anthracite, white) as variants.",
    "'Kein Gift, kein Strom' ist ein klarer Pluspunkt gegenüber elektrischen Vernichtern — Eltern und Tierhalter wählen Lure bewusst.": "'No poison, no electricity' is a clear advantage over electric zappers — parents and pet owners deliberately choose Lure.",
    "Cross-Listing-Strategie: in Listing-Bildern direkt zur elektrischen Alternative abgrenzen. 'Sicher für Kinder, Hunde, Katzen' im ersten Bullet.": "Cross-listing strategy: differentiate from electric alternatives directly in listing images. 'Safe for kids, dogs, cats' in the first bullet.",
    "Mehrwegfallen halten mehrere Saisons — Käufer kommen für Nachfüllköder zurück, aber müssen aktiv suchen.": "Reusable traps last multiple seasons — buyers come back for refill bait but have to search actively.",
    "Nachfüll-Subscription (Saisonstart + Mitte Sommer) als Subscribe-and-Save aufsetzen. Cross-Sell in der Verpackung der Erstfalle einlegen.": "Refill subscription (season start + mid-summer) via Subscribe-and-Save. Cross-sell insert in the original trap packaging.",
    "Wespen am Esstisch / BBQ": "Wasps at the dinner table / BBQ",
    "Klassischer Hauptanwendungsfall — Sommer draußen essen ohne Wespen.": "Classic primary use case — summer dining outside without wasps.",
    "Schutz im Garten / auf der Terrasse": "Protection in the garden / on the patio",
    "Ganztägig nutzbarer Außenbereich ohne Wespen-Belästigung.": "All-day usable outdoor area without wasp harassment.",
    "Bei Wespennest in der Nähe": "When a wasp nest is nearby",
    "Wespennest unter Dach/im Schuppen entdeckt — Falle als Sofortmaßnahme.": "Wasp nest spotted under the roof/in the shed — trap as an immediate measure.",
    "Obstbäume / Fallobst-Saison": "Fruit trees / fallen-fruit season",
    "Reife Pflaumen, Birnen oder Äpfel locken Wespen massiv an.": "Ripe plums, pears or apples attract wasps in droves.",
    "Hauseingang / Tür freihalten": "Doorway / keeping the door clear",
    "Wespen am Hauseingang sollen ferngehalten werden, damit Tür sicher offen bleibt.": "Keeping wasps away from the doorway so the door can safely stay open.",
    "Präventiv vor der Saison": "Pre-emptive before the season",
    "Königinnen im Frühjahr abfangen — verhindert große Völker im Sommer.": "Catch queens in spring — prevents large colonies in summer.",
    "Endlich ungestört draußen sitzen": "Finally sitting outside undisturbed",
    "Pain-driven Kauf nach Sommer mit Wespen-Plage am Esstisch.": "Pain-driven purchase after a summer with a wasp plague at the dinner table.",
    "Familie/Kinder vor Stichen schützen": "Protecting family/kids from stings",
    "Kleinkinder und Wespenstich-Angst — emotionaler Trigger.": "Toddlers and fear of wasp stings — emotional trigger.",
    "Allergie-Schutz": "Allergy protection",
    "Wespenstich-Allergiker kaufen prophylaktisch und mehrfach.": "Wasp-sting allergy sufferers buy prophylactically and repeatedly.",
    "Alternative zu Strom/Chemie": "Alternative to electricity/chemicals",
    "Bewusste Käufer wollen weder Insektizide noch elektrische Geräte.": "Conscious buyers want neither insecticides nor electric devices.",
    "BBQ-/Grillabende retten": "Saving BBQ evenings",
    "Speziell Grillabende sollen wieder störungsfrei stattfinden.": "BBQ evenings specifically should be undisturbed again.",
    "Dekorative Lösung statt Industrie-Look": "Decorative solution instead of industrial look",
    "Falle hängt sichtbar — Optik soll zum Garten passen.": "Trap hangs visibly — looks should fit the garden.",
    "Fängt wirklich Wespen": "Actually catches wasps",
    "Erwartung Nummer eins — wenn 'Wespenfalle' draufsteht, sollen auch Wespen drin sein.": "Top expectation — if it says 'wasp trap', wasps should actually be inside.",
    "Schont Bienen & Nützlinge": "Spares bees & beneficials",
    "Selektivität wird zunehmend erwartet — auch von Nicht-Imker-Kunden.": "Selectivity is increasingly expected — even by non-beekeeper customers.",
    "Köder hält mindestens 2 Wochen": "Bait lasts at least 2 weeks",
    "Wer alle 3 Tage nachfüllen muss, fühlt sich getäuscht.": "Anyone who has to refill every 3 days feels misled.",
    "Einfache, ekel-freie Reinigung": "Easy, gross-free cleaning",
    "No-Touch-Entleerung wird inzwischen als Standard erwartet.": "No-touch emptying is now expected as standard.",
    "Wetterfest für ganze Saison": "Weatherproof for the whole season",
    "Falle soll Sommer durchhalten ohne brüchig oder ausgebleicht zu werden.": "Trap should survive summer without becoming brittle or faded.",
    "Sicher für Kinder & Haustiere": "Safe for kids & pets",
    "Kein Gift, keine offenen Drähte, gut befestigt.": "No poison, no exposed wires, securely mounted.",
    "Alle Themen": "All themes",
    "Zieht Bienen, Hummeln & Fliegen an": "Attracts bees, bumblebees & flies",
    "Köder trocknet/verdunstet zu schnell": "Bait dries out / evaporates too fast",
    "Geruch zu stark / ekelhaft": "Smell too strong / disgusting",
    "Zu teuer für das Gebotene": "Too expensive for what you get",
    "Beschädigt geliefert": "Arrived damaged",
    "Wetter / Wind / Sonne": "Weather / wind / sun",
    "Einfach aufzustellen": "Easy to set up",
    "Sicher & ungiftig": "Safe & non-toxic",
    "Unauffälliges/dekoratives Design": "Discreet/decorative design",
    "Gutes Preis-Leistungs-Verhältnis": "Good value for money",
    "Lockstoff funktioniert": "Bait works",

    # ── DE Electric ──────────────────────────────────────────────────────────
    "Kernzielgruppe sind <b>Garten- und Terrassennutzer</b> sowie <b>Familien mit Kindern</b>, die im Sommer und besonders während der <b>Grillsaison</b> nach einer Lösung gegen Wespen, Mücken und Fliegen suchen. Indoor-Einsatz im <b>Schlafzimmer</b> und in der <b>Gastronomie</b> sind die zwei stärksten Zweit-Use-Cases.": "Core audience: <b>garden and patio users</b> plus <b>families with children</b> looking for a solution against wasps, mosquitoes and flies in summer, especially during <b>BBQ season</b>. Indoor use in the <b>bedroom</b> and in <b>restaurants/cafes</b> are the two strongest secondary use cases.",
    "Bei <b>1275</b> Reviews dominiert das Thema <b>Wirksamkeit gegen Wespen</b> — viele Geräte fangen primär Mücken und Fliegen. Sekundär kritisch: <b>Bienen-Tötung</b>, <b>Lautstärke</b> und <b>UV-Blendung</b>. Positiv hervorgehoben werden <b>sichtbarer Erfolg</b> (volle Schale), <b>einfache Reinigung</b> und <b>Sicherheit für Kinder</b>.": "Across <b>1275</b> reviews, <b>effectiveness against wasps</b> dominates — many devices primarily catch mosquitoes and flies. Secondary pain: <b>killing bees</b>, <b>noise</b> and <b>UV glare</b>. Top praise: <b>visible success</b> (full tray), <b>easy cleaning</b>, and <b>safety for children</b>.",
    "Bei Wespen-/Insektenplage": "Insect/wasp invasion",
    "Nachts (Schlafen)": "Night (sleep)",
    "Ganzjährig (Innenbereich)": "Year-round (indoor)",
    "Schlafzimmer": "Bedroom",
    "Wohnzimmer/Küche": "Living room/Kitchen",
    "Gastronomie": "Restaurant/cafe",
    "Lagerräume": "Storage/shed",
    "Carport": "Carport",
    "UV-Insektenvernichter": "UV bug zapper",
    "Stromnetz-Falle": "Electric grid trap",
    "Vakuum-Falle": "Vacuum trap",
    "Tragbar/Solar": "Portable/Solar",
    "Wandmontage": "Wall-mounted",
    "Steckdosengerät": "Plug-in indoor",
    "Häufigster Frust: das Gerät tötet zwar Mücken oder Fliegen, aber gegen Wespen schlägt es nicht an.": "Top frustration: the device kills mosquitoes or flies but doesn't work against wasps.",
    "38 von 407 negativen Bewertungen (9.3%) berichten von Wirkungslosigkeit": "38 of 407 negative reviews (9.3%) report ineffectiveness",
    "Wespen werden nicht vom UV-Licht angezogen — gilt für mehrere Modelle": "Wasps aren't attracted to UV light — applies to multiple models",
    "Hauptbeschwerde quer über alle ASINs": "Main complaint across all ASINs",
    "Erwartung 'Wespenfalle' wird oft nicht erfüllt — eher Mücken-/Fliegenfänger": "Expectation 'wasp trap' often unmet — more of a mosquito/fly catcher",
    "Schwer zu reinigen / Verarbeitung": "Hard to clean / build quality",
    "Auffangschale schwer abnehmbar, Plastikteile brechen, Reinigungsbürste fehlt oder ist unbrauchbar.": "Catch tray hard to remove, plastic parts break, cleaning brush missing or unusable.",
    "6.4% (26) mit Verarbeitungs- oder Reinigungsproblemen": "6.4% (26) with build or cleaning issues",
    "Auffangschale verklemmt oder schwer entnehmbar": "Catch tray jams or is hard to remove",
    "Plastikclips brechen nach wenigen Wochen": "Plastic clips break after a few weeks",
    "Reinigungspinsel fehlt oder ist zu klein": "Cleaning brush missing or too small",
    "Zu lautes Knistern/Knallen": "Loud crackling/zapping noise",
    "Lautes Zerplatzen der Insekten stört vor allem nachts oder beim Essen draußen.": "Loud bursting of insects is disturbing especially at night or while eating outside.",
    "7 Reviews (1.7%) bemängeln Knistern oder Knallen": "7 reviews (1.7%) complain about crackling or zapping",
    "Besonders im Schlafzimmer und nachts störend": "Especially disturbing in the bedroom and at night",
    "Lautstärke unterschätzt — vor Kauf nicht erwartet": "Noise underestimated — not expected before purchase",
    "Auch Lüftergeräusch der Vakuummodelle wird kritisiert": "Fan noise of vacuum models is also criticised",
    "Sicherheitsbedenken": "Safety concerns",
    "Offene Drähte, zu großes Schutzgitter — Sorge um Kinder, Haustiere oder Brandgefahr.": "Exposed wires, oversized protective grid — concern about children, pets or fire hazard.",
    "3 Reviews (0.7%) mit Sicherheitsbedenken": "3 reviews (0.7%) with safety concerns",
    "Schutzgitter zu großmaschig — Finger oder Pfote passen durch": "Protective grid too wide-meshed — fingers or paws fit through",
    "Geräte werden im Betrieb sehr heiß": "Devices get very hot during operation",
    "Brandgefahr bei längerem unbeaufsichtigtem Betrieb": "Fire hazard with prolonged unattended operation",
    "Funktioniert sehr effektiv": "Very effective",
    "Auffangschale füllt sich innerhalb von Stunden — sichtbarer Erfolg überzeugt.": "Catch tray fills within hours — visible success convinces.",
    "80 von 711 positiven Bewertungen (11.3%) loben die Wirksamkeit": "80 of 711 positive reviews (11.3%) praise the effectiveness",
    "Volle Auffangschale binnen Stunden — sichtbarer Beweis": "Full catch tray within hours — visible proof",
    "Mücken- und Fliegenwirkung deutlich besser als Wespenwirkung": "Mosquito and fly effect notably better than wasp effect",
    "Einsatz im Stall oder in der Küche überzeugt am meisten": "Use in barns or kitchens is most convincing",
    "Langlebig & robust": "Durable & robust",
    "Mehrjährige Nutzung ohne Defekt wird mehrfach erwähnt.": "Multi-year use without defects is mentioned repeatedly.",
    "60 (8.4%) berichten von langer Lebensdauer": "60 (8.4%) report long lifespan",
    "Mehrere Sommer ohne Defekt im Einsatz": "Multiple summers in use without defects",
    "Robuste Verarbeitung wird gelobt": "Sturdy build quality is praised",
    "Ersatz-UV-Röhren erhältlich verlängern Lebensdauer": "Replacement UV tubes available extend lifespan",
    "Funktion plus Verarbeitung rechtfertigen den Preis im Vergleich zu teureren Marken.": "Function plus build quality justify the price compared to more expensive brands.",
    "2.5% (18) heben gutes Preis-Leistungs-Verhältnis hervor": "2.5% (18) highlight good value for money",
    "Verarbeitung wirkt deutlich teurer als der Kaufpreis": "Build feels notably more expensive than the price tag",
    "Mehrere Saisonen Nutzung amortisieren den Preis": "Multi-season use amortises the price",
    "Günstiger als professionelle Schädlingsbekämpfung": "Cheaper than professional pest control",
    "Schickes Design": "Stylish design",
    "Geräte werden sichtbar in Wohnraum oder auf Terrasse aufgestellt — Design zählt.": "Devices are placed visibly in living spaces or on the patio — design matters.",
    "11 (1.5%) finden das Design gelungen": "11 (1.5%) find the design well done",
    "Geräte werden bewusst sichtbar aufgestellt": "Devices are deliberately placed visibly",
    "Modernes Erscheinungsbild — kein klassisches Industriedesign": "Modern appearance — not classic industrial design",
    "Auch im Wohnzimmer oder Restaurant präsentabel": "Presentable in the living room or restaurant too",
    "Engmaschiges Schutzgitter beruhigt Familien mit Kleinkindern oder neugierigen Katzen.": "Fine-mesh protective grid reassures families with toddlers or curious cats.",
    "1.4% (10) loben Sicherheit für Kinder und Haustiere": "1.4% (10) praise safety for children and pets",
    "Engmaschiges Schutzgitter beruhigt Eltern": "Fine-mesh protective grid reassures parents",
    "Katzenpfoten kommen nicht ans Hochspannungsgitter": "Cat paws can't reach the high-voltage grid",
    "Wandmontage erhöht Sicherheit zusätzlich": "Wall mounting adds extra safety",
    "Großer Wirkungsbereich": "Large coverage area",
    "Ein Gerät reicht für ganze Räume oder größere Terrassenbereiche.": "One device covers entire rooms or larger patio areas.",
    "4 (0.6%) loben großen Wirkungsbereich": "4 (0.6%) praise large coverage area",
    "Reicht für ganze Räume oder größere Terrassen": "Covers entire rooms or larger patios",
    "Ein Gerät spart mehrere Einzelfallen": "One device replaces multiple single traps",
    "Effektreichweite mehrere Meter": "Effective range of several metres",
    "Kunden kaufen 'Wespenfalle', erhalten aber primär einen Mücken- und Fliegenkiller — UV-Licht zieht keine Wespen an.": "Customers buy 'wasp trap' but get primarily a mosquito and fly killer — UV light doesn't attract wasps.",
    "Listings müssen entweder Wespenwirkung wissenschaftlich belegen (CO2-Lockstoff, Pheromon) oder den Anwendungsfall ehrlich auf Mücken/Fliegen verschieben — sonst dominieren Erwartungs-Lücken die Bewertungen.": "Listings must either scientifically prove wasp efficacy (CO2 lure, pheromone) or honestly reposition to mosquitoes/flies — otherwise expectation gaps dominate the reviews.",
    "Bienen-, Hummel- und Schmetterlingstode treiben einen relevanten Anteil der 1-Stern-Reviews — besonders unter Garten- und Imker-Kunden.": "Bee, bumblebee and butterfly deaths drive a significant share of 1-star reviews — especially among garden and beekeeper customers.",
    "Selektivität (z. B. Lockstoffe, die nur Wespen anziehen, oder selektive Gitterabstände) als USP herausstellen. Andernfalls Imker-Segment komplett aus Targeting nehmen und Kommunikation 'Innenraum' fokussieren.": "Highlight selectivity (e.g. baits that attract only wasps, or selective grid spacing) as a USP. Otherwise drop the beekeeper segment entirely from targeting and focus messaging on 'indoor'.",
    "Knister-/Knallgeräusch beim Insektentod und Lüfterbrummen stören vor allem im Schlafzimmer und beim BBQ.": "Crackling/zapping sound on insect death and fan hum are disturbing especially in the bedroom and during BBQs.",
    "Vakuum-Variante oder Klebefolie statt Hochspannung als 'Schlafzimmer-tauglich' positionieren. Lautstärke in dB explizit im Listing kommunizieren.": "Position a vacuum variant or sticky-paper version instead of high voltage as 'bedroom-suitable'. State noise in dB explicitly in the listing.",
    "Helles UV-Licht stört nachts und blendet Nachbarn auf der Terrasse — Top-3-Nicht-Effizienz-Beschwerde.": "Bright UV light is disturbing at night and dazzles neighbours on the patio — top-3 non-efficacy complaint.",
    "Dimmer, Timer oder gerichteter Reflektor sind klare Differenzierungs-Features. Mindestens im Listing 'Lichtintensität' mit Lux-Wert angeben.": "Dimmer, timer or directional reflector are clear differentiating features. At minimum, state 'light intensity' with lux value in the listing.",
    "Auffangschale schwer entnehmbar, Reinigungspinsel fehlt oder ist unbrauchbar — wiederkehrendes Thema.": "Catch tray hard to remove, cleaning brush missing or unusable — recurring theme.",
    "'Tool-free Cleaning' und spülmaschinengeeignete Schale sind low-cost Features mit hohem Review-Impact. Im Bullet-Point #2 oder #3 hervorheben.": "'Tool-free cleaning' and dishwasher-safe tray are low-cost features with high review impact. Highlight in bullet #2 or #3.",
    "Outdoor-Versprechen wird bei Regen oft nicht eingehalten — Geräte fallen aus oder werden dauerhaft beschädigt.": "Outdoor promise often not kept in rain — devices fail or get permanently damaged.",
    "Klare IP-Klassen-Kommunikation (IP44, IP54) plus 'auch bei Dauerregen' als Bild im A+. Indoor-Modelle nicht für Outdoor-Targeting verwenden.": "Clear IP-class communication (IP44, IP54) plus 'even in continuous rain' as A+ image. Don't target outdoor use for indoor models.",
    "Volle Auffangschale binnen Stunden ist der stärkste Wow-Effekt — Kunden teilen Fotos in Reviews.": "Full catch tray within hours is the biggest wow effect — customers share photos in reviews.",
    "Hero-Image im Listing sollte volle Schale + Datumsstempel zeigen. UGC-Foto-Kampagne für 'before/after' hat hohen ROI.": "Listing hero image should show a full tray plus date stamp. UGC photo campaign for 'before/after' has high ROI.",
    "'Leise' und 'störungsfrei nachts' sind in positiven Reviews stark vertreten — neuer Use Case neben Garten.": "'Quiet' and 'undisturbed at night' are strongly represented in positive reviews — new use case alongside garden.",
    "Eigene Listing-Variante 'für das Schlafzimmer' mit Dimm-Funktion und niedriger Lautstärke. Erschließt Allergiker- und Mücken-Segment im Innenraum.": "Dedicated listing variant 'for the bedroom' with dimming function and low noise. Unlocks the allergy-sufferer and mosquito indoor segment.",
    "Eltern und Tierhalter loben Schutzgitter und Wandmontage — entscheidet bei Familienkauf.": "Parents and pet owners praise the protective grid and wall mounting — decisive for family purchases.",
    "Sicherheits-Icon (TÜV, GS, Kindersicher) und Wandhalterung im Lieferumfang prominent kommunizieren. A+-Modul mit Familie/Kind/Katze.": "Communicate safety icons (TÜV, GS, child-safe) and include the wall bracket in the box prominently. A+ module with family/child/cat.",
    "'Schickes Design' rechtfertigt höheren Preis — moderne Optik wird sichtbar im Wohnraum aufgestellt.": "'Stylish design' justifies a higher price — modern looks placed visibly in the living room.",
    "Lifestyle-Bilder statt Industrie-Look. Premium-Variante mit 30 % Preisaufschlag und 'Wohnzimmer-Design' als Differenzierung.": "Lifestyle images instead of industrial look. Premium variant at +30% price with 'living-room design' as differentiator.",
    "Akku-/Tragbar-Modelle werden wechselnd drinnen und draußen genutzt — verlängert Saisonnutzung.": "Battery/portable models are used indoors and outdoors interchangeably — extends seasonal use.",
    "Akku-Variante als ganzjähriges Produkt vermarkten (nicht nur Sommer). Bundle mit Wandhalterung + Standfuß.": "Market the battery variant as a year-round product (not just summer). Bundle with wall bracket + stand.",
    "Mehrere Saisons Nutzung ohne Defekt wird mehrfach genannt — schlägt das No-Name-Vorurteil.": "Multi-season use without defects is mentioned repeatedly — beats the no-name prejudice.",
    "2- oder 3-Jahres-Garantie als USP. Ersatz-UV-Röhren als Cross-Sell-Position.": "2- or 3-year warranty as a USP. Replacement UV tubes as a cross-sell position.",
    "Mücken/Wespen auf der Terrasse": "Mosquitoes/wasps on the patio",
    "Klassischer Hauptanwendungsfall — Sommerabend draußen ohne Insekten-Belästigung.": "Classic primary use case — summer evening outside without insect harassment.",
    "Schlafzimmer / nachts ruhig schlafen": "Bedroom / sleeping quietly at night",
    "Mücken im Schlafzimmer — UV-Lampe als nächtliche Abhilfe.": "Mosquitoes in the bedroom — UV lamp as a night-time remedy.",
    "Gastronomie / Verkaufsraum": "Restaurant / retail space",
    "Hygienisch wichtig — Restaurants, Cafés, Imbisse setzen es ganzjährig ein.": "Hygiene-critical — restaurants, cafes, takeaways use it year-round.",
    "Stall / Lager / Werkstatt": "Barn / warehouse / workshop",
    "Tierhaltung und Lagerräume mit konstantem Fliegen-/Mücken-Aufkommen.": "Animal husbandry and storage rooms with constant fly/mosquito presence.",
    "Wohnzimmer / Küche": "Living room / kitchen",
    "Drinnen rund ums Essen — Mücken und Fliegen weg vom Tisch halten.": "Indoors around food — keeping mosquitoes and flies away from the table.",
    "BBQ / Grillsaison": "BBQ season",
    "Grillabend ohne Wespen am Steak — explizit als Anwendung erwähnt.": "BBQ evening without wasps on the steak — explicitly mentioned as a use case.",
    "Endlich Ruhe vor Wespen/Mücken": "Finally peace from wasps/mosquitoes",
    "Pain-driven Kauf nach konkretem Plagejahr oder Stich-Erlebnis.": "Pain-driven purchase after a specific bad year or stinging incident.",
    "Familie/Kinder schützen": "Protecting family/kids",
    "Sicherheit für Kleinkinder vor Wespenstichen — emotionaler Trigger.": "Safety for toddlers from wasp stings — emotional trigger.",
    "Outdoor-Lifestyle ungestört genießen": "Enjoying outdoor lifestyle undisturbed",
    "Garten, Terrasse, Pool — wer Sommer draußen verbringt, will keine Insekten.": "Garden, patio, pool — anyone spending summer outside doesn't want insects.",
    "Hygiene im Verkaufsraum": "Hygiene in retail/dining spaces",
    "Gastronomie/Verkauf braucht Insektenschutz aus Hygiene- und Imagegründen.": "Restaurants/retail need insect control for hygiene and brand-image reasons.",
    "Wespenstich-Allergiker kaufen prophylaktisch.": "Wasp-sting allergy sufferers buy prophylactically.",
    "Alternative zu Sprays/Chemie": "Alternative to sprays/chemicals",
    "Bewusste Käufer wollen keine Insektizide im Wohnraum.": "Conscious buyers don't want insecticides in living spaces.",
    "Wirkt wirklich gegen Wespen": "Actually works against wasps",
    "Erwartung Nummer eins — wenn 'Wespenfalle' draufsteht, soll sie auch Wespen fangen.": "Top expectation — if it says 'wasp trap', it should actually catch wasps.",
    "Leiser Betrieb": "Quiet operation",
    "Kein lautes Knallen oder Lüfterbrummen, vor allem nachts.": "No loud zapping or fan hum, especially at night.",
    "Ökologisch bewusste Käufer wollen keine Kollateralschäden.": "Eco-conscious buyers don't want collateral damage.",
    "Kindersicher & haustiersicher": "Child- & pet-safe",
    "Familien erwarten engmaschiges Schutzgitter und sichere Befestigung.": "Families expect a fine-mesh protective grid and secure mounting.",
    "Einfache Reinigung": "Easy cleaning",
    "Tray rausziehen, ausklopfen, fertig — kein Putz-Aufwand.": "Pull out the tray, tap it out, done — no scrubbing required.",
    "Wetterfest für Outdoor": "Weatherproof for outdoor",
    "Bei Outdoor-Modellen wird Regenfestigkeit erwartet — auch ohne ausdrückliche IP-Angabe.": "Rain resistance is expected for outdoor models — even without an explicit IP rating.",
    "Tötet Bienen & Nützlinge": "Kills bees & beneficials",
    "UV-Licht zu hell / blendet": "UV light too bright / dazzling",
    "Hoher Stromverbrauch": "High power consumption",
    "Nicht wetterfest": "Not weatherproof",
    "Drinnen wie draußen einsetzbar": "Indoor and outdoor use",

    # ── FR Lure ──────────────────────────────────────────────────────────────
    "<b>1405</b> avis analysés sur <b>9 ASINs Lure</b> du marché FR (BSI domine avec 3 références et 672 avis ; Protecta, Mice&Co et Barrière à Insectes complètent le top). Acheteurs majoritairement <b>propriétaires de maison avec jardin/terrasse</b>, avec une forte présence de familles cherchant une <b>solution sans insecticide</b> autour des espaces de vie extérieurs.": "<b>1,405</b> reviews analysed across <b>9 Lure ASINs</b> in the FR market (BSI dominates with 3 SKUs and 672 reviews; Protecta, Mice&Co and Barrière à Insectes round out the top). Buyers are mostly <b>homeowners with a garden/patio</b>, with a strong presence of families looking for an <b>insecticide-free solution</b> around outdoor living spaces.",
    "Top frustration : <b>manque d'efficacité</b>. Top atout : <b>très efficace</b>. Les attentes du marché FR convergent autour de l'efficacité visible rapidement, de la sélectivité (épargner les abeilles) et de l'intégration discrète à la terrasse — terrain favorable à un piège à appât gel longue tenue, sans sucre, format suspendu sobre.": "Top frustration: <b>lack of efficacy</b>. Top strength: <b>very effective</b>. FR market expectations converge on quick visible results, selectivity (sparing bees), and discreet integration into the patio — fertile ground for a long-lasting gel-bait trap, sugar-free, in a sober hanging format.",
    "Propriétaires": "Homeowners",
    "Jardin/Terrasse": "Garden/patio users",
    "Parents/Enfants": "Parents with kids",
    "Allergiques": "Allergy sufferers",
    "Restaurateurs": "Restaurant/cafe owners",
    "Apiculteurs": "Beekeepers",
    "Démarrage printemps": "Spring start",
    "Pic d'été": "Summer peak",
    "Saison BBQ": "BBQ season",
    "Après nid trouvé": "After spotting nest",
    "Préventif": "Pre-emptive (before season)",
    "Fin de saison": "End of season",
    "Terrasse/Jardin": "Garden/patio",
    "Arbres fruitiers": "Fruit trees",
    "Repas extérieur": "Outdoor dining",
    "Près des fenêtres": "Near doors/windows",
    "Sous l'auvent": "Eaves/overhang",
    "Piège suspendu": "Hanging trap with bait",
    "Sachet d'appât": "Bait sachet",
    "Piège cloche": "Reusable bell trap",
    "Piège-bouteille": "Bottle trap",
    "Piège jetable": "Disposable bag trap",
    "Piège collant fenêtre": "Window sticky trap",
    "Manque d'efficacité": "Doesn't catch wasps / ineffective",
    "Le piège ne capture aucune ou très peu de guêpes selon de nombreux acheteurs.": "Many buyers report the trap catches no or very few wasps.",
    "Aucune guêpe capturée même après plusieurs semaines d'exposition.": "No wasps caught even after several weeks of exposure.",
    "Les guêpes voient le piège mais ne rentrent pas dedans.": "Wasps see the trap but don't enter it.",
    "Plus efficace pour les mouches que pour les guêpes selon plusieurs avis.": "More effective for flies than for wasps, according to several reviews.",
    "Décevant comparé à un piège artisanal (bouteille + sirop).": "Disappointing compared to a DIY trap (bottle + syrup).",
    "Attire les mauvais insectes": "Attracts the wrong insects",
    "Attire mouches, moucherons, abeilles ou frelons au lieu des guêpes.": "Attracts flies, gnats, bees or hornets instead of wasps.",
    "Beaucoup de mouches et moucherons piégés à la place des guêpes.": "Lots of flies and gnats trapped instead of wasps.",
    "Risque réel pour les abeilles, qui se retrouvent prises.": "Real risk for bees, which end up trapped.",
    "Quelques cas de frelons attrapés — bénéfice mais aussi danger.": "A few cases of hornets caught — useful but also dangerous.",
    "Trompeur si l'on cherche un piège ciblé guêpes uniquement.": "Misleading if you're looking for a wasp-specific trap.",
    "Mauvaise odeur": "Bad smell",
    "Odeur de l'appât jugée nauséabonde ou insupportable près des espaces de vie.": "Bait smell rated nauseating or unbearable near living spaces.",
    "Odeur très forte qui empêche d'en profiter à proximité.": "Very strong smell that prevents enjoying nearby areas.",
    "Senteur de sucre fermenté difficile à supporter sur la terrasse.": "Fermented-sugar smell hard to tolerate on the patio.",
    "Odeur de guêpes en décomposition au bout de quelques jours.": "Smell of decomposing wasps after a few days.",
    "À éloigner des fenêtres et de la table à manger.": "Needs to be kept away from windows and the dining table.",
    "Prix trop élevé": "Overpriced",
    "Tarif jugé excessif au regard des résultats obtenus.": "Price rated excessive given the results delivered.",
    "Prix élevé au regard de la quantité d'appât fournie.": "High price for the amount of bait included.",
    "Coût cumulé recharges + piège jugé excessif sur la saison.": "Combined cost of refills + trap rated excessive over the season.",
    "Comparé à un piège-bouteille DIY, le rapport résultat/prix déçoit.": "Compared to a DIY bottle trap, the price/result ratio disappoints.",
    "Plusieurs acheteurs trouvent l'écart prix/efficacité trop important.": "Several buyers find the price/efficacy gap too wide.",
    "Tenue aux intempéries": "Weather durability",
    "Décoloration, casse ou perte d'efficacité après pluie, soleil ou vent.": "Discolouration, breakage or efficacy loss after rain, sun or wind.",
    "Couleur qui jaunit ou plastique qui craque après quelques semaines au soleil.": "Colour yellows or plastic cracks after a few weeks in the sun.",
    "Vent renverse les modèles à poser au sol.": "Wind knocks over the ground-standing models.",
    "Pluie qui dilue l'appât liquide et réduit son efficacité.": "Rain dilutes the liquid bait and reduces efficacy.",
    "Durabilité limitée à une saison pour beaucoup d'utilisateurs.": "Durability limited to one season for many users.",
    "Conception du piège": "Trap design",
    "Difficile à nettoyer, fragile, fuites ou montage compliqué.": "Hard to clean, fragile, leaks or complicated assembly.",
    "Difficile à nettoyer une fois rempli de guêpes mortes.": "Hard to clean once filled with dead wasps.",
    "Plastique trop fin qui se brise au montage ou à l'usage.": "Plastic too thin, breaks during assembly or use.",
    "Fuites de liquide attractif qui salissent la terrasse.": "Attractant liquid leaks and stains the patio.",
    "Système de fermeture peu pratique pour vider le piège.": "Closing system inconvenient when emptying the trap.",
    "Appât qui sèche": "Bait dries out",
    "L'appât se dessèche ou se cristallise rapidement, perdant son attractivité.": "Bait dries out or crystallises quickly, losing its attractiveness.",
    "L'appât liquide s'évapore en quelques jours par forte chaleur.": "Liquid bait evaporates within days in hot weather.",
    "Cristallisation du sucre qui bloque l'entrée du piège.": "Sugar crystallisation blocks the trap entrance.",
    "Recharge nécessaire bien plus souvent qu'annoncé.": "Refills needed far more often than advertised.",
    "Coût caché : il faut multiplier les recharges sur la saison.": "Hidden cost: refills add up over the season.",
    "Livraison abîmée": "Arrived damaged",
    "Produit reçu cassé, fissuré ou endommagé pendant le transport.": "Product received broken, cracked or damaged in transit.",
    "Pièges reçus cassés ou fissurés dès l'ouverture du colis.": "Traps received broken or cracked on opening the package.",
    "Emballage trop léger pour protéger un produit en plastique fin.": "Packaging too flimsy to protect a thin-plastic product.",
    "Liquide d'appât renversé pendant le transport.": "Bait liquid spilled during transit.",
    "Retours / remboursements parfois compliqués à obtenir.": "Returns/refunds sometimes complicated to obtain.",
    "Très efficace": "Very effective",
    "Capture rapidement de nombreuses guêpes, parfois en quelques jours.": "Catches many wasps quickly, sometimes within days.",
    "Pièges remplis en quelques jours dès la mise en place.": "Traps fill within days of being set up.",
    "Diminution nette du nombre de guêpes autour des repas en extérieur.": "Clear reduction in wasps around outdoor meals.",
    "Fonctionne particulièrement bien en plein été et en saison BBQ.": "Works particularly well in mid-summer and BBQ season.",
    "Beaucoup d'acheteurs commandent un second piège après essai.": "Many buyers order a second trap after trying it.",
    "Idéal en extérieur": "Perfect for outdoor use",
    "Parfaitement adapté à la terrasse, au jardin, autour des repas en plein air.": "Perfectly suited for the patio, garden, around outdoor meals.",
    "Parfait suspendu dans un arbre ou sous une pergola.": "Perfect hung from a tree or under a pergola.",
    "Très utilisé autour des repas en terrasse et au bord de la piscine.": "Heavily used around patio meals and by the pool.",
    "Apprécié des propriétaires d'arbres fruitiers en fin de saison.": "Appreciated by fruit-tree owners at end of season.",
    "Plébiscité pour les barbecues et les apéros en extérieur.": "Highly praised for BBQs and outdoor drinks.",
    "Sûr pour enfants & animaux": "Safe for kids & pets",
    "Solution non toxique, sans insecticide, rassurante en présence d'enfants ou d'animaux.": "Non-toxic, insecticide-free solution, reassuring around children or pets.",
    "Solution rassurante avec enfants ou animaux à proximité.": "Reassuring solution with children or pets nearby.",
    "Pas d'insecticide pulvérisé dans l'air ambiant.": "No insecticide sprayed into the ambient air.",
    "Préféré aux sprays par les familles.": "Preferred over sprays by families.",
    "Adapté aux jardins fréquentés par chiens et chats.": "Suited to gardens visited by dogs and cats.",
    "Facile à utiliser": "Easy to use",
    "Montage et installation simples, prêt à l'emploi en quelques minutes.": "Simple assembly and installation, ready to use in minutes.",
    "Quelques minutes suffisent pour le monter et le suspendre.": "A few minutes is enough to assemble and hang it.",
    "Aucun outil nécessaire, instructions claires.": "No tools needed, clear instructions.",
    "Recharge / vidage rapide d'une saison à l'autre.": "Quick refill/emptying from one season to the next.",
    "Convient même aux utilisateurs qui n'ont jamais utilisé de piège.": "Works even for users who've never used a trap.",
    "Design discret": "Discreet design",
    "Apparence sobre ou décorative qui s'intègre bien sur la terrasse ou au jardin.": "Sober or decorative appearance that fits in well on the patio or in the garden.",
    "Aspect discret qui s'intègre bien sur une terrasse ou un balcon.": "Discreet look that fits in well on a patio or balcony.",
    "Format suspendu compact, peu visible à distance.": "Compact hanging format, barely visible from a distance.",
    "Plusieurs modèles décoratifs jugés plus jolis qu'un piège-bouteille DIY.": "Several decorative models rated prettier than a DIY bottle trap.",
    "Plaît particulièrement à ceux qui veulent un produit visible mais soigné.": "Particularly appealing to those who want a visible but tasteful product.",
    "Longue tenue": "Long-lasting",
    "Le piège ou l'appât dure plusieurs semaines, voire toute la saison.": "The trap or bait lasts several weeks, sometimes the whole season.",
    "Tient toute la saison estivale sans intervention.": "Lasts the whole summer season without intervention.",
    "Résiste à plusieurs semaines d'exposition extérieure.": "Withstands several weeks of outdoor exposure.",
    "Modèle réutilisable d'une année à l'autre avec une simple recharge.": "Reusable model from year to year with a simple refill.",
    "Durée d'efficacité de l'appât appréciée comparé à d'autres marques.": "Bait effectiveness duration appreciated compared to other brands.",
    "44.3% des avis négatifs disent que le piège \"ne capture rien\" ou n'attire aucune guêpe — premier motif d'insatisfaction sur le marché FR.": "44.3% of negative reviews say the trap 'catches nothing' or attracts no wasps — top dissatisfaction driver on the FR market.",
    "Surcommuniquer le délai d'amorçage (5–10 jours pour saturer l'appât d'odeur) et préciser la zone d'efficacité réaliste (~20 m²) pour aligner les attentes avant achat.": "Over-communicate the priming time (5–10 days to saturate the bait with scent) and state realistic coverage (~20 m²) to align expectations pre-purchase.",
    "42.0% des plaintes portent sur l'attraction d'autres insectes — surtout mouches et abeilles, point de friction très français.": "42.0% of complaints are about attracting other insects — especially flies and bees, a very French friction point.",
    "Mettre en avant un appât \"sans sucre/sans miel\" (à base de protéines ou de phéromones) et afficher clairement \"ne piège pas les abeilles\" en visuel principal — argument différenciant sur ce marché.": "Lead with a 'sugar-free/honey-free' bait (protein- or pheromone-based) and clearly state 'does not trap bees' on the hero image — differentiating argument on this market.",
    "1.9% mentionnent un piège fragile, fuites ou difficile à nettoyer (BSI et regional brands ciblés).": "1.9% mention a fragile trap, leaks or hard to clean (BSI and regional brands targeted).",
    "Investir dans un système de vidage par dévissage hermétique et une notice photo française. Whitespace face aux 3 ASINs BSI dominants (672 avis) qui souffrent de ce reproche récurrent.": "Invest in a hermetic screw-off emptying system and a French photo guide. Whitespace versus the 3 dominant BSI ASINs (672 reviews) that suffer from this recurring complaint.",
    "1.0% se plaignent que l'appât sèche ou cristallise — coût caché en recharges.": "1.0% complain the bait dries or crystallises — hidden refill cost.",
    "Proposer un appât gel longue tenue (8 semaines garanties) ou format recharge multi-saison à prix calibré, point d'entrée pour bâtir une relation récurrente.": "Offer a long-lasting gel bait (8 weeks guaranteed) or multi-season refill at calibrated pricing, entry point for building a recurring relationship.",
    "7.1% évoquent une odeur insupportable près de la table ou des fenêtres — friction directe avec l'usage \"repas en terrasse\".": "7.1% report an unbearable smell near the table or windows — direct friction with the 'patio dining' use case.",
    "Décliner une version \"odeur masquée\" (capsule fermée, diffusion contrôlée) et recommander des distances d'installation dans la fiche produit pour éviter cette déception.": "Launch a 'masked-odour' version (sealed capsule, controlled diffusion) and recommend placement distances in the product description to avoid this disappointment.",
    "3.1% signalent une dégradation après pluie ou exposition UV (jaunissement, casse).": "3.1% report degradation after rain or UV exposure (yellowing, breakage).",
    "Communiquer une garantie \"saison entière\" (juin → septembre) et utiliser un plastique stabilisé UV. Étiquette « résiste aux intempéries » très attendue par les acheteurs FR.": "Communicate a 'whole season' warranty (June → September) and use UV-stabilised plastic. 'Weather-resistant' label highly expected by FR buyers.",
    "53.5% des avis 4-5★ louent l'efficacité réelle, souvent avec des photos de pièges remplis.": "53.5% of 4-5★ reviews praise real-world efficacy, often with photos of full traps.",
    "Capitaliser sur le UGC photo (\"avant/après\", \"piège plein en X jours\") dans les images A+ et la PPC. Surpondérer la preuve visuelle, c'est le déclencheur n°1 du marché FR.": "Capitalise on UGC photos ('before/after', 'trap full in X days') in A+ images and PPC. Over-index on visual proof — it's the #1 trigger on the FR market.",
    "3.7% saluent la simplicité d'installation — point fort transversal aux marques BSI, Protecta, Mice&Co.": "3.7% praise the simplicity of installation — a cross-brand strength of BSI, Protecta, Mice&Co.",
    "Conserver le \"prêt à l'emploi\" comme bullet 1, ajouter un mini-tuto vidéo 30 s en image 7 pour amplifier ce signal positif déjà acquis.": "Keep 'ready to use' as bullet 1, add a 30-sec mini-tutorial video as image 7 to amplify this already-positive signal.",
    "5.2% rassurent sur l'absence d'insecticide, motif d'achat clé chez les familles françaises.": "5.2% reassure about the absence of insecticide, a key purchase driver among French families.",
    "Mettre en avant un badge \"sans insecticide\" / \"adapté familles\" en image principale. Storytelling autour des enfants jouant au jardin protège du churn.": "Lead with an 'insecticide-free' / 'family-friendly' badge on the hero image. Storytelling around children playing in the garden protects against churn.",
    "1.8% confirment que le piège tient toute la saison.": "1.8% confirm the trap lasts the whole season.",
    "Promettre clairement « 1 piège = 1 saison » avec icône calendrier dans les images. Rassure sur le ROI face au piège DIY hebdomadaire.": "Clearly promise '1 trap = 1 season' with a calendar icon in the images. Reassures on ROI versus the weekly DIY trap.",
    "11.7% détaillent un usage terrasse/jardin/repas en extérieur — usage très ancré dans la culture FR.": "11.7% detail patio/garden/outdoor-meal use — deeply rooted in French culture.",
    "Construire les visuels lifestyle autour de ces 3 scènes (table dressée, jardin estival, pergola). Le marché US/UK n'a pas le même attachement aux repas dehors.": "Build lifestyle visuals around these 3 scenes (set table, summer garden, pergola). The US/UK market doesn't have the same attachment to outdoor dining.",
    "3.3% apprécient un design discret, signal différenciant face aux pièges-bouteilles DIY.": "3.3% appreciate a discreet design, a differentiating signal versus DIY bottle traps.",
    "Tester un coloris terre cuite ou vert sauge dans la gamme : niche premium peu adressée par BSI/Protecta, alignée à la sensibilité esthétique des acheteurs FR de terrasse.": "Test a terracotta or sage-green colourway in the range: premium niche underserved by BSI/Protecta, aligned with the aesthetic sensibility of FR patio buyers.",
    "Préventif avant l'été": "Pre-emptive before summer",
    "Installé tôt en saison pour intercepter les reines fondatrices.": "Set up early in the season to intercept founding queens.",
    "Protection jardin / piscine": "Garden / pool protection",
    "Suspendu dans le jardin ou autour de la piscine pour réduire la pression de guêpes.": "Hung in the garden or around the pool to reduce wasp pressure.",
    "Repas et apéros en terrasse": "Patio meals and drinks",
    "Posé près des tables pour profiter des repas dehors sans être harcelé par les guêpes.": "Placed near tables to enjoy outdoor meals without wasp harassment.",
    "Arbres fruitiers en fin de saison": "Fruit trees at end of season",
    "Accroché dans les pommiers, poiriers ou figuiers pour protéger les fruits mûrs.": "Hung in apple, pear or fig trees to protect ripe fruit.",
    "Balcon en appartement": "Apartment balcony",
    "Format compact pour balcons et petits espaces urbains.": "Compact format for balconies and small urban spaces.",
    "Famille avec enfants": "Family with children",
    "Solution sans insecticide installée à proximité des espaces de jeu.": "Insecticide-free solution placed near play areas.",
    "Lutte saisonnière": "Seasonal control",
    "Anticipation de la saison estivale ou réaction à une invasion locale.": "Anticipating the summer season or reacting to a local invasion.",
    "Recommandé / déjà testé": "Recommended / previously tried",
    "Achat sur conseil de proches ou renouvellement d'un produit déjà concluant.": "Bought on recommendation from family/friends or repurchase of a previously successful product.",
    "Alternative aux pièges DIY": "Alternative to DIY traps",
    "Cherche un produit prêt à l'emploi plutôt que la classique bouteille + sirop.": "Looking for a ready-to-use product rather than the classic bottle + syrup.",
    "Protéger les enfants / animaux": "Protect children / pets",
    "Inquiétude pour les piqûres sur enfants ou animaux dans le jardin.": "Concern about stings on children or pets in the garden.",
    "Profiter de l'extérieur tranquille": "Enjoying the outdoors in peace",
    "Pouvoir manger dehors, jardiner ou recevoir sans être harcelé par les guêpes.": "Being able to eat outside, garden or entertain without wasp harassment.",
    "Solution sans insecticide": "Insecticide-free solution",
    "Pas envie de pulvériser de produits chimiques près des enfants, animaux ou de la nourriture.": "No desire to spray chemicals near children, pets or food.",
    "Résistance aux intempéries": "Weather resistance",
    "Tenir au soleil, à la pluie et au vent toute la saison estivale.": "Withstand sun, rain and wind throughout the summer season.",
    "Capture immédiate visible": "Immediate visible capture",
    "Les acheteurs attendent de voir des guêpes piégées en quelques heures à quelques jours.": "Buyers expect to see wasps trapped within hours to days.",
    "Sélectivité guêpes uniquement": "Wasp-only selectivity",
    "Souhait fort que le piège n'attrape pas mouches, abeilles ou frelons.": "Strong desire that the trap doesn't catch flies, bees or hornets.",
    "Facilité de nettoyage": "Easy cleaning",
    "Vider et rincer le piège doit rester rapide et sans contact avec les insectes morts.": "Emptying and rinsing the trap must stay quick and contact-free with dead insects.",
    "Discrétion visuelle": "Visual discretion",
    "Doit s'intégrer à la terrasse ou au jardin sans être trop voyant.": "Must blend into the patio or garden without being too conspicuous.",
    "Appât longue durée": "Long-lasting bait",
    "L'appât doit tenir plusieurs semaines sans recharge, même par forte chaleur.": "Bait must last several weeks without refill, even in hot weather.",
    "🔴 Manque d'efficacité": "🔴 Doesn't catch wasps / ineffective",
    "🔴 Attire les mauvais insectes": "🔴 Attracts the wrong insects",
    "🔴 Appât qui sèche": "🔴 Bait dries out",
    "🔴 Conception du piège": "🔴 Trap design",
    "🔴 Mauvaise odeur": "🔴 Bad smell",
    "🔴 Prix trop élevé": "🔴 Overpriced",
    "🔴 Livraison abîmée": "🔴 Arrived damaged",
    "🔴 Tenue aux intempéries": "🔴 Weather durability",
    "🟢 Très efficace": "🟢 Very effective",
    "🟢 Facile à utiliser": "🟢 Easy to use",
    "🟢 Sûr pour enfants & animaux": "🟢 Safe for kids & pets",
    "🟢 Design discret": "🟢 Discreet design",
    "🟢 Bon rapport qualité-prix": "🟢 Good value for money",
    "🟢 Appât efficace": "🟢 Bait works",
    "🟢 Longue tenue": "🟢 Long-lasting",
    "🟢 Idéal en extérieur": "🟢 Perfect for outdoor use",

    # ── FR Electric ──────────────────────────────────────────────────────────
    "Les <b>1107 acheteurs</b> de raquettes/lampes électriques sur amazon.fr sont majoritairement des <b>particuliers</b> qui veulent éliminer mouches et moustiques à la maison (cuisine, salon, chambre) — pas des chasseurs de guêpes. Sous-segments importants : <b>familles avec enfants/animaux</b> (alternative aux sprays), <b>vanlifers et campeurs</b> (format USB nomade), et <b>hôteliers/restaurateurs</b> qui achètent en multipack pour équiper plusieurs pièces.": "The <b>1,107 buyers</b> of electric swatters/lamps on amazon.fr are mostly <b>individuals</b> who want to eliminate flies and mosquitoes at home (kitchen, living room, bedroom) — not wasp hunters. Key sub-segments: <b>families with children/pets</b> (alternative to sprays), <b>vanlifers and campers</b> (portable USB format), and <b>hoteliers/restaurateurs</b> who buy in multipacks to equip several rooms.",
    "Sentiment fortement <b>polarisé</b> : <b>40.3%</b> d'avis positifs (4-5★) vs. <b>59.7%</b> de négatifs (1-3★), avec une concentration énorme sur le 1★ (30%). Quand l'unité fonctionne, elle est qualifiée de 'redoutable' (mouches, moustiques) et l'acheteur en achète parfois 4-6 de plus pour équiper hôtels/chambres. Quand elle tombe en panne (batterie HS, ne se recharge plus, casse), c'est radical : retour, 1-étoile, et dans plusieurs cas alerte sécurité (surchauffe, fonte du connecteur USB-C). Les 3 marques (YISSVIC, GeckoMan, Jawlark) montrent le même schéma — c'est un défaut de catégorie, pas de marque. La qualité du module batterie/charge est le seul vrai différenciateur durable possible sur ce marché.": "Sentiment is strongly <b>polarised</b>: <b>40.3%</b> positive (4-5★) vs. <b>59.7%</b> negative (1-3★), with a huge concentration on 1★ (30%). When the unit works, it's described as 'devastating' (flies, mosquitoes) and the buyer sometimes orders 4-6 more to equip hotels/rooms. When it fails (dead battery, won't recharge, breakage), it's drastic: return, 1-star, and in several cases a safety alert (overheating, melted USB-C connector). The 3 brands (YISSVIC, GeckoMan, Jawlark) show the same pattern — it's a category defect, not a brand one. Battery/charge module quality is the only real durable differentiator possible on this market.",
    "Propriétaires / particuliers": "Homeowners / individuals",
    "Utilisateurs jardin/terrasse": "Garden/patio users",
    "Parents avec enfants": "Parents with kids",
    "Allergiques / piqués": "Allergy sufferers / bite-prone",
    "Restaurateurs / hôteliers": "Restaurant/hotel owners",
    "Voyageurs / vanlife": "Travellers / vanlife",
    "Propriétaires d'animaux": "Pet owners",
    "Saison BBQ / repas en plein air": "BBQ season / outdoor meals",
    "Invasion d'insectes": "Insect invasion",
    "La nuit / pour dormir": "Night (sleep)",
    "Toute l'année (intérieur)": "Year-round (indoor)",
    "Terrasse / Jardin": "Garden/patio",
    "Chambre / Pour dormir": "Bedroom",
    "Salon / Cuisine": "Living room/Kitchen",
    "Restaurant / Hôtel": "Restaurant/hotel",
    "Van / Camping-car": "Van / Camper",
    "Garage / Cave / Stockage": "Storage/shed",
    "Raquette électrique rechargeable": "Rechargeable electric swatter",
    "Lampe UV / piège lumineux": "UV bug zapper",
    "Pivotant / pliable": "Pivoting / foldable",
    "Modèle 2-en-1 (raquette + base)": "2-in-1 model (swatter + base)",
    "USB rechargeable": "USB rechargeable",
    "Avec rallonge / perche": "With extension pole",
    "Inefficace — ne tue ni mouches ni moustiques": "Ineffective — doesn't kill flies or mosquitoes",
    "Plainte n°1 : la raquette/lampe ne tue rien, les insectes s'envolent ou sont juste 'assommés' puis repartent.": "Complaint #1: the swatter/lamp doesn't kill anything, insects fly off or are merely 'stunned' then leave.",
    "276 avis (41.8% du négatif) déclarent que la raquette ou le piège lumineux ne tue tout simplement pas — les insectes touchent la grille puis repartent.": "276 reviews (41.8% of negatives) report the swatter or light trap simply doesn't kill — insects touch the grid then fly off.",
    "Schéma récurrent : zap audible mais l'insecte se relève au bout de quelques secondes — le voltage est jugé insuffisant face aux gros insectes (mouches vertes, guêpes).": "Recurring pattern: audible zap but the insect recovers after a few seconds — voltage rated too low for large insects (green flies, wasps).",
    "Mode automatique sur socle : la lumière est jugée trop faible pour attirer quoi que ce soit, surtout en pièce éclairée.": "Auto mode on stand: the light is rated too weak to attract anything, especially in a lit room.",
    "Comparaison récurrente : 'autant utiliser une tapette à 5 €' — l'écart attendu vs. la solution traditionnelle n'est pas perçu.": "Recurring comparison: 'might as well use a €5 swatter' — the expected gap vs. the traditional solution is not perceived.",
    "Batterie meurt / ne se recharge plus": "Battery dies / won't recharge",
    "Après quelques semaines à quelques mois, l'appareil ne tient plus la charge ou refuse de se recharger — produit transformé en 'usage unique'.": "After a few weeks to a few months, the device no longer holds charge or refuses to recharge — turning the product into 'single-use'.",
    "214 avis (32.4% du négatif) rapportent que la batterie ne tient plus la charge ou refuse de se recharger après quelques semaines.": "214 reviews (32.4% of negatives) report the battery no longer holds a charge or refuses to recharge after a few weeks.",
    "Mode de défaillance le plus cité : se charge normalement (LED rouge ok) puis ne s'allume pas une fois débranché — l'appareil devient 'jetable après 1-2 mois'.": "Most-cited failure mode: charges normally (red LED OK) then won't switch on once unplugged — the device becomes 'disposable after 1-2 months'.",
    "Connecteur USB-C s'écrase ou se déforme — plusieurs photos 1-étoile montrent le port de charge fondu ou décollé.": "USB-C connector crushes or deforms — several 1-star photos show the charging port melted or detached.",
    "Délais de retour Amazon (30 j) souvent dépassés au moment de la panne — frustration amplifiée par l'impossibilité de retour.": "Amazon's 30-day return window often exceeded by the time the failure occurs — frustration amplified by inability to return.",
    "Casse au bout d'1-3 mois": "Breaks after 1-3 months",
    "Défaillance prématurée généralisée : socle, fils, plastique, connecteur USB — la raquette devient HS bien avant la fin de la première saison d'usage.": "Widespread early failure: base, wires, plastic, USB connector — the swatter dies well before the end of the first usage season.",
    "177 avis (26.8% du négatif) constatent une panne définitive entre 1 semaine et 6 mois après l'achat.": "177 reviews (26.8% of negatives) report a permanent failure between 1 week and 6 months after purchase.",
    "Les pannes touchent toutes les pièces : grille (fil cassé), socle (instable, casse), chargeur (ne se branche plus), batterie (HS).": "Failures hit every part: grid (broken wire), base (wobbly, breaks), charger (won't plug in), battery (dead).",
    "Plusieurs acheteurs en sont à leur 2e ou 3e raquette (parfois la même marque) — accepté comme consommable saisonnier, mais frustrant à ce niveau de prix.": "Several buyers are on their 2nd or 3rd swatter (sometimes the same brand) — accepted as seasonal consumable, but frustrating at this price point.",
    "Lumière UV trop faible — n'attire rien": "UV light too weak — attracts nothing",
    "Le mode lampe est jugé inutile : la LED bleue est trop faible pour attirer mouches et moustiques, surtout en extérieur ou en pièce éclairée.": "Lamp mode is rated useless: the blue LED is too weak to attract flies and mosquitoes, especially outdoors or in a lit room.",
    "124 avis se plaignent que la LED bleue UV est trop faible pour attirer mouches et moustiques en mode passif.": "124 reviews complain the UV blue LED is too weak to attract flies and mosquitoes in passive mode.",
    "Le mode 'piège lumineux' (raquette posée sur socle, allumée la nuit) est jugé inopérant — les insectes ignorent totalement la lumière.": "The 'light trap' mode (swatter on stand, lit at night) is rated ineffective — insects completely ignore the light.",
    "En extérieur (terrasse, balcon), aucun effet — la luminosité est noyée dans l'éclairage ambiant.": "Outdoors (patio, balcony), no effect — the brightness is drowned out by ambient lighting.",
    "Bruit / claquement gênant la nuit": "Loud zap / annoying at night",
    "À chaque insecte zappé, un 'pétard' sec — empêche de dormir si l'appareil reste en mode auto la nuit.": "With every insect zapped, a sharp 'crack' — prevents sleep if the device stays in auto mode at night.",
    "73 avis évoquent le 'pétard' bruyant à chaque insecte zappé — au point de réveiller la nuit.": "73 reviews mention the loud 'crack' on each insect zapped — to the point of waking people at night.",
    "Le mode auto (raquette allumée toute la nuit en chambre) est rendu impraticable par le bruit — paradoxe : le mode censé protéger le sommeil empêche de dormir.": "Auto mode (swatter on all night in the bedroom) is made impractical by the noise — paradox: the mode meant to protect sleep prevents it.",
    "Ajouter un mode 'silencieux nuit' ou un voyant LED visuel à la place du claquement est un besoin produit clair.": "Adding a 'silent night' mode or a visual LED indicator in place of the crack is a clear product need.",
    "Défauts de conception (grille, socle, chargeur)": "Design flaws (grid, base, charger)",
    "Cadre épais qui empêche les insectes de toucher la grille, socle instable, chargeur défectueux dès la livraison — le produit n'est pas pensé pour durer.": "Thick frame stopping insects from touching the grid, wobbly base, charger faulty out of the box — the product isn't designed to last.",
    "63 avis identifient des défauts de conception : grille protectrice trop épaisse (l'insecte ne touche pas la grille active), socle instable, chargeur dès la livraison défectueux.": "63 reviews identify design flaws: protective grid too thick (insects don't touch the active grid), wobbly base, charger faulty out of the box.",
    "Les acheteurs comparent négativement avec 'l'ancienne raquette 5 €' qui avait moins de gadgets mais touchait l'insecte directement.": "Buyers compare unfavourably with 'the old €5 swatter' which had fewer gadgets but actually touched the insect.",
    "Le cordon USB est jugé trop court pour atteindre les prises hautes — plusieurs avis 4★ baissent à cause de ce détail.": "The USB cord is rated too short to reach high outlets — several 4★ reviews drop because of this detail.",
    "Trop cher pour ce que c'est": "Overpriced for what it is",
    "À 25-30 €, les acheteurs déçus comparent avec des modèles à 5 € en grande surface qui 'tiennent aussi bien'.": "At €25-30, disappointed buyers compare with €5 supermarket models that 'last just as well'.",
    "46 avis (7.0% du négatif) jugent le prix (25-30 €) injustifié face à la durabilité réelle.": "46 reviews (7.0% of negatives) rate the price (€25-30) as unjustified given real-world durability.",
    "Référence comparative spontanée : 'Leclerc en vend une à 5 €' — la valeur perçue est largement amputée par les pannes.": "Spontaneous comparison: 'Leclerc sells one for €5' — perceived value heavily eroded by failures.",
    "Plusieurs avis s'interrogent sur le marketing : 'la rallonge en plastique est strictement inutile, du pur marketing!'": "Several reviews question the marketing: 'the plastic extension is strictly useless, pure marketing!'",
    "Dangereux — surchauffe, fond, prend feu": "Dangerous — overheats, melts, catches fire",
    "Plusieurs reviews 1-étoile rapportent que l'appareil chauffe anormalement, fond au niveau du connecteur USB-C ou même prend feu en charge.": "Several 1-star reviews report the device heats abnormally, melts at the USB-C connector or even catches fire while charging.",
    "38 avis (5.8% du négatif) rapportent que l'appareil a fondu en charge, surchauffé, voire pris feu — risque sécurité réel.": "38 reviews (5.8% of negatives) report the device melted while charging, overheated, or caught fire — real safety risk.",
    "Une cliente signale que sa raquette branchée sur la même multiprise qu'un PC a 'grillé' le PC à 700 € — possible défaut de protection contre les surtensions.": "One customer reports her swatter, plugged into the same power strip as a PC, 'fried' the €700 PC — possible defect in surge protection.",
    "Demande à clarifier les certifications (CE, RoHS) sur la fiche produit — la confiance sécurité est aujourd'hui basse.": "Demand to clarify certifications (CE, RoHS) on the product page — safety trust is currently low.",
    "Très efficace — extermine mouches & moustiques": "Very effective — exterminates flies & mosquitoes",
    "Les fans rapportent une efficacité 'redoutable' contre mouches et moustiques, surtout en mode actif (raquette en main).": "Fans report 'devastating' efficacy against flies and mosquitoes, especially in active mode (swatter in hand).",
    "284 avis 4-5★ qualifient l'appareil de 'super efficace' / 'redoutable' contre mouches et moustiques en mode actif.": "284 4-5★ reviews call the device 'super effective' / 'devastating' against flies and mosquitoes in active mode.",
    "Le mode 'raquette en main' est plébiscité : zap immédiat, satisfaction visuelle (étincelle bleue + claquement) — les utilisateurs 'kiffent' le geste.": "The 'swatter in hand' mode is highly praised: instant zap, visual satisfaction (blue spark + crack) — users 'love' the gesture.",
    "Particulièrement efficace en intérieur la nuit — la combinaison faible lumière ambiante + raquette tenue donne le meilleur taux de prise.": "Particularly effective indoors at night — the combination of low ambient light + handheld swatter gives the best catch rate.",
    "Tête pivotante atteint le plafond": "Pivoting head reaches the ceiling",
    "USP majeur de GeckoMan : la rallonge + tête orientable permet d'éliminer les insectes au plafond sans grimper sur une chaise.": "GeckoMan's key USP: the extension + pivoting head lets you kill ceiling insects without climbing on a chair.",
    "118 avis 5★ mentionnent la rallonge amovible + tête pivotante comme la raison principale du choix de GeckoMan vs. les concurrents.": "118 5★ reviews cite the removable extension + pivoting head as the main reason for choosing GeckoMan over competitors.",
    "Cas d'usage récurrent : remplacement d'une raquette précédente sans rallonge — le 'monter sur une chaise' était l'irritant.": "Recurring use case: replacement of a previous swatter without extension — 'climbing on a chair' was the friction point.",
    "Particulièrement loué pour les moucherons au plafond, mais aussi araignées, frelons, mouches dans les coins hauts.": "Particularly praised for ceiling gnats, but also spiders, hornets, flies in high corners.",
    "USB rechargeable — fini les piles": "USB rechargeable — no more batteries",
    "L'autonomie sur batterie USB est saluée comme un vrai progrès vs. les anciennes raquettes à piles.": "USB battery autonomy is hailed as a real step forward vs. old battery-powered swatters.",
    "102 avis positifs saluent le passage à USB rechargeable (vs. piles AA) — autonomie de plusieurs semaines en usage normal.": "102 positive reviews welcome the move to USB rechargeable (vs. AA batteries) — autonomy of several weeks in normal use.",
    "La possibilité de la laisser sur son socle de charge en permanence est un confort apprécié.": "The ability to leave it permanently on its charging dock is an appreciated comfort.",
    "Particulièrement utile pour usage nomade (van, camping, hôtels).": "Particularly useful for portable use (van, camping, hotels).",
    "Polyvalent — maison, terrasse, van, camping": "Versatile — home, patio, van, camping",
    "Utilisé partout : cuisine, chambre, terrasse, balcon, van, camping-car — l'autonomie batterie en fait un compagnon nomade.": "Used everywhere: kitchen, bedroom, patio, balcony, van, camper — battery autonomy makes it a portable companion.",
    "83 avis évoquent un usage en intérieur (cuisine, chambre, salon) ET en mobilité (van, camping-car, camping).": "83 reviews mention indoor use (kitchen, bedroom, living room) AND mobile use (van, camper, camping).",
    "Cas d'usage hôtelier intéressant : un avis évoque l'équipement de 5 chambres d'hôtel — multipack B2B clair.": "Interesting hotel use case: one review mentions equipping 5 hotel rooms — clear B2B multipack opportunity.",
    "Multiplie les achats : 'une dans chaque pièce', '4 chambres équipées', preuve d'effet d'engagement.": "Multiplies purchases: 'one in each room', '4 rooms equipped', proof of engagement effect.",
    "Sans produit chimique — ok familles & animaux": "Chemical-free — OK for families & pets",
    "Mode mécanique (zap électrique vs. spray) rassure les parents et propriétaires d'animaux — pas de chimie dans la maison.": "Mechanical mode (electric zap vs. spray) reassures parents and pet owners — no chemicals in the home.",
    "63 avis insistent sur le côté 'sans chimie' — mode mécanique (zap) vs. sprays insecticides.": "63 reviews emphasise the 'chemical-free' angle — mechanical mode (zap) vs. insecticide sprays.",
    "Argument santé décisif chez parents, allergiques, propriétaires d'animaux.": "Decisive health argument for parents, allergy sufferers, pet owners.",
    "Clientèle anti-spray : 'bombe insecticide, vinaigre de cidre, savon noir, rien n'y faisait. J'ai acheté cette raquette et j'ai été éradiqué le moucheron.'": "Anti-spray customer base: 'insecticide bomb, cider vinegar, black soap, nothing worked. I bought this swatter and the gnats were wiped out.'",
    "Bon rapport qualité-prix (quand ça marche)": "Good value (when it works)",
    "Pour les unités qui fonctionnent durablement, le prix est jugé justifié — alternative naturelle aux sprays chimiques.": "For units that work reliably, the price is rated justified — natural alternative to chemical sprays.",
    "42 avis : pour les unités qui durent, le prix (25-30 €) est jugé justifié vs. les sprays chimiques répétés sur la saison.": "42 reviews: for units that last, the price (€25-30) is rated justified vs. repeated chemical sprays over the season.",
    "Plusieurs acheteurs (hôteliers, restaurateurs) en achètent 4-6 unités d'un coup pour équiper toutes les chambres — preuve de confiance produit.": "Several buyers (hoteliers, restaurateurs) buy 4-6 units at once to equip all rooms — proof of product confidence.",
    "Cas de rachat : 'TIPTOP en ai acheté un deuxième', 'jamais déçu, 2ème achat'.": "Repurchase cases: 'TIPTOP bought a second one', 'never disappointed, 2nd purchase'.",
    "La batterie/charge USB lâche entre 1 semaine et 6 mois après l'achat — le défaut #1 vu chez les 3 marques (YISSVIC, GeckoMan, Jawlark).": "Battery/USB charge fails between 1 week and 6 months after purchase — defect #1 seen across the 3 brands (YISSVIC, GeckoMan, Jawlark).",
    "Améliorer le module batterie + connecteur USB-C est la priorité absolue pour réduire le taux de retour. Communiquer une garantie batterie 12 mois explicite dans la fiche produit pour rassurer.": "Improving the battery module + USB-C connector is the absolute priority to reduce returns. Communicate an explicit 12-month battery warranty on the product page to reassure.",
    "Plusieurs avis 1-étoile signalent surchauffe, fonte du connecteur USB-C en charge, voire incendie — risque de rappel produit.": "Several 1-star reviews report overheating, USB-C connector melting while charging, even fire — product-recall risk.",
    "Audit qualité usine + ajout protection thermique + mise en avant des certifications CE/RoHS dans la fiche. Un seul incident viral (TikTok / forum) peut tuer une marque sur cette catégorie.": "Factory quality audit + add thermal protection + highlight CE/RoHS certifications on the page. A single viral incident (TikTok / forum) can kill a brand in this category.",
    "Vendu/recherché comme solution 'guêpes' mais conçu/utilisé surtout pour mouches et moustiques — déception inévitable des acheteurs ciblant les guêpes.": "Sold/searched as a 'wasp' solution but designed/used mainly for flies and mosquitoes — inevitable disappointment for wasp-focused buyers.",
    "Repositionner explicitement la fiche : 'efficace contre mouches, moustiques, moucherons — usage limité contre guêpes (plusieurs zaps nécessaires)'. Aligne attentes et baisse les 1-étoile pour mauvaise raison.": "Explicitly reposition the page: 'effective against flies, mosquitoes, gnats — limited use against wasps (multiple zaps needed)'. Aligns expectations and reduces 1-star reviews for wrong reasons.",
    "Le claquement à chaque zap empêche d'utiliser le mode auto la nuit en chambre — paradoxal pour un produit anti-moustiques.": "The crack on each zap prevents using auto mode at night in the bedroom — paradoxical for an anti-mosquito product.",
    "Ajouter un 'mode silencieux nuit' (réduction du voltage / signal LED visuel à la place du son) — innovation produit simple et différenciante sur Amazon.": "Add a 'silent night mode' (reduced voltage / visual LED instead of sound) — simple, differentiating product innovation on Amazon.",
    "Le mode lampe-piège passif ne fonctionne pas : LED bleue trop faible pour attirer en pièce éclairée ou en extérieur.": "The passive light-trap mode doesn't work: blue LED too weak to attract in a lit room or outdoors.",
    "Soit retirer la promesse 'lampe-piège' du marketing, soit upgrader vers une vraie LED UV-A (365 nm) plus puissante. Sinon, la fonction décrédibilise le produit.": "Either drop the 'light-trap' promise from marketing, or upgrade to a real UV-A LED (365 nm) with more power. Otherwise the feature undermines the product.",
    "30-40% des reviews FR proviennent en réalité de UK/US/DE/ES/IT/AE — beaucoup de '1-étoile' génériques en anglais qui font baisser la moyenne FR.": "30-40% of FR reviews actually come from UK/US/DE/ES/IT/AE — many generic '1-star' English-language reviews dragging down the FR average.",
    "Marketing : la perception par un client français est plus positive que ne le laisse penser le score global. Mettre en avant les avis filtrés FR dans le storytelling A+.": "Marketing: French customers' perception is more positive than the overall score suggests. Highlight FR-filtered reviews in the A+ storytelling.",
    "Atteindre les insectes au plafond est l'argument 5★ #1 pour GeckoMan (rallonge + tête pivotante).": "Reaching ceiling insects is the #1 5★ argument for GeckoMan (extension + pivoting head).",
    "Hero shot : main qui zappe une mouche au plafond, sans chaise. Vidéo principale : 'fini les mouches au plafond'. Cet usage seul justifie le prix premium vs. raquettes basiques.": "Hero shot: hand zapping a fly on the ceiling, no chair. Main video: 'no more ceiling flies'. This use case alone justifies the premium price vs. basic swatters.",
    "Forte demande chez vanlifers, campeurs, hôteliers — l'autonomie USB en fait un produit nomade utile, pas un simple gadget de cuisine.": "Strong demand among vanlifers, campers, hoteliers — USB autonomy makes it a useful portable product, not just a kitchen gadget.",
    "Bundle 2x (van + maison) ou pack 4x pour hôteliers/Airbnb. Marketing dédié 'pack camping-car'. Élargit le TAM bien au-delà du marché 'maison'.": "2x bundle (van + home) or 4x pack for hoteliers/Airbnb. Dedicated 'camper pack' marketing. Expands TAM well beyond the 'home' market.",
    "Argument santé fort chez parents et propriétaires d'animaux — alternative crédible aux sprays insecticides.": "Strong health argument among parents and pet owners — credible alternative to insecticide sprays.",
    "Badge 'Sans produit chimique — 100% mécanique' bien visible sur l'image principale. Renforce le ciblage familles, qui est un segment à forte LTV (achat répété).": "'Chemical-free — 100% mechanical' badge prominently visible on the hero image. Reinforces family targeting, a high-LTV segment (repeat purchases).",
    "Plusieurs reviews 5★ insistent sur le 'plaisir' du zap — étincelle bleue + claquement = retour visuel/sonore satisfaisant.": "Several 5★ reviews emphasise the 'pleasure' of the zap — blue spark + crack = satisfying audio/visual feedback.",
    "Marketing émotionnel : viser le 'satisfying clip' style TikTok. La catégorie est sous-investie en contenu social — opportunité de différenciation marketing.": "Emotional marketing: aim for the 'satisfying clip' TikTok style. The category is under-invested in social content — marketing differentiation opportunity.",
    "Avis répétés d'hôteliers/restaurateurs achetant 4-6 unités à la fois pour équiper toutes les chambres.": "Repeated reviews from hoteliers/restaurateurs buying 4-6 units at a time to equip every room.",
    "Lister un pack 4x ou 6x avec un PUM réduit pour la cible B2B. Possibilité de remontée d'AOV (+150-200%) sans cannibaliser la cible particulière.": "List a 4x or 6x pack at reduced unit price for the B2B target. Possible AOV uplift (+150-200%) without cannibalising the consumer target.",
    "La fonction 2-en-1 (raquette + lampe sur socle) est un argument d'achat — même si l'efficacité du mode lampe est contestée.": "The 2-in-1 function (swatter + lamp on stand) is a purchase argument — even if lamp-mode efficacy is contested.",
    "Communiquer clairement les deux modes mais éviter de survendre la fonction lampe (cf. negative insight). Rester sur 'raquette principale + bonus lampe d'appoint'.": "Clearly communicate both modes but avoid over-selling the lamp function (see negative insight). Stay with 'main swatter + bonus auxiliary lamp'.",
    "Tuer mouches / moustiques en intérieur (salon / cuisine / chambre)": "Kill flies/mosquitoes indoors (living room/kitchen/bedroom)",
    "Usage le plus fréquent : raquette en main pour éliminer les insectes volants dans la maison, surtout l'été quand les fenêtres sont ouvertes.": "Most frequent use: swatter in hand to eliminate flying insects in the home, especially in summer when windows are open.",
    "Insectes au plafond — atteindre sans grimper": "Ceiling insects — reach without climbing",
    "Cas d'usage différenciant pour les modèles avec rallonge + tête pivotante (GeckoMan).": "Differentiating use case for models with extension + pivoting head (GeckoMan).",
    "Protection terrasse / jardin pendant les repas": "Patio/garden protection during meals",
    "Raquette ou lampe sur socle pour protéger les apéros et BBQ en extérieur, principalement en été.": "Swatter or lamp on stand to protect outdoor drinks and BBQs, mainly in summer.",
    "Lampe-piège passive sur socle 24h/24": "Passive light-trap on stand 24/7",
    "Raquette posée sur socle, allumée en mode auto pour attirer les insectes la nuit (efficacité contestée).": "Swatter on stand, lit in auto mode to attract insects at night (efficacy contested).",
    "Familles avec enfants / animaux — solution sans chimie": "Families with kids / pets — chemical-free solution",
    "Alternative mécanique aux sprays insecticides, choisie par les parents et propriétaires d'animaux.": "Mechanical alternative to insecticide sprays, chosen by parents and pet owners.",
    "Vie nomade — van / camping / hôtel": "Nomadic life — van / camping / hotel",
    "Usage mobile en camping-car, van, ou pour équiper plusieurs chambres dans un hôtel ou gîte.": "Mobile use in camper, van, or to equip several rooms in a hotel or B&B.",
    "Éliminer les mouches/moustiques de la maison": "Eliminate flies/mosquitoes from the home",
    "Motivation #1 : se débarrasser des insectes volants en intérieur, surtout l'été quand les fenêtres sont ouvertes.": "Motivation #1: get rid of flying insects indoors, especially in summer when windows are open.",
    "Atteindre les insectes au plafond": "Reach ceiling insects",
    "Spécifique aux modèles avec rallonge — résoudre le problème 'monter sur une chaise pour tuer la mouche'.": "Specific to models with extension — solving the 'climb on a chair to kill the fly' problem.",
    "Alternative aux sprays chimiques (santé)": "Alternative to chemical sprays (health)",
    "Parents et propriétaires d'animaux veulent éviter les insecticides à pulvériser dans la maison.": "Parents and pet owners want to avoid spraying insecticides in the home.",
    "Usage nomade — van / camping": "Nomadic use — van / camping",
    "Vanlifers, campeurs, voyageurs — autonomie batterie + format compact.": "Vanlifers, campers, travellers — battery autonomy + compact format.",
    "Équipement multi-chambres (hôtel / gîte)": "Multi-room equipment (hotel / B&B)",
    "Achat en série par les hôteliers, gîtes ruraux et locations saisonnières.": "Bulk purchase by hoteliers, rural B&Bs and seasonal rentals.",
    "Remplacement d'une vieille raquette à piles": "Replacement of an old battery-powered swatter",
    "Upgrade depuis un modèle plus ancien — passage USB rechargeable + features.": "Upgrade from an older model — move to USB rechargeable + features.",
    "Cadeau / curiosité (gadget satisfying)": "Gift / curiosity (satisfying gadget)",
    "Achat impulsif ou cadeau — la dimension 'satisfaction visuelle du zap' est un driver.": "Impulse buy or gift — the 'visual satisfaction of the zap' dimension is a driver.",
    "Batterie qui dure plusieurs saisons": "Battery lasts multiple seasons",
    "L'attente principale : que la batterie tienne au moins 12 mois d'usage normal. Aujourd'hui, 1 raquette sur 3-4 lâche avant.": "Top expectation: battery should last at least 12 months of normal use. Today, 1 in 3-4 swatters fails before then.",
    "Tue les insectes du premier coup": "Kills insects on the first hit",
    "Voltage suffisant pour tuer mouche/moustique en un seul zap — pas besoin de 'frapper plusieurs fois'.": "Sufficient voltage to kill a fly/mosquito in one zap — no need to 'hit multiple times'.",
    "Connecteur USB-C robuste": "Robust USB-C connector",
    "Le port de charge ne doit pas s'écraser, fondre ou se déformer après quelques recharges — défaut #2 le plus cité.": "The charging port shouldn't crush, melt or deform after a few recharges — the 2nd most-cited defect.",
    "Lampe UV qui attire vraiment": "UV lamp that actually attracts",
    "Si le mode lampe-piège est annoncé, qu'il fonctionne — sinon, le retirer du marketing.": "If light-trap mode is advertised, it should work — otherwise drop it from marketing.",
    "Mode silencieux pour la nuit": "Silent mode for night",
    "Alternative au 'pétard' bruyant pour pouvoir laisser l'appareil allumé en chambre.": "Alternative to the loud 'crack' so the device can be left on in the bedroom.",
    "Garantie 12 mois explicite": "Explicit 12-month warranty",
    "Délai de retour Amazon 30 j insuffisant face à la durée de vie réelle — couverture étendue exigée.": "Amazon's 30-day return window inadequate vs. real lifespan — extended coverage demanded.",
    "Inefficace / ne tue pas": "Ineffective / doesn't kill",
    "Batterie / charge HS": "Battery / charge dead",
    "Casse rapidement": "Breaks quickly",
    "Lumière trop faible": "Light too weak",
    "Bruit / claquement": "Noise / crack",
    "Dangereux / surchauffe": "Dangerous / overheats",
    "Défauts de conception": "Design flaws",
    "Reçu endommagé": "Arrived damaged",
    "Trop cher": "Overpriced",
    "Tue mauvais insectes / inutile": "Kills wrong insects / useless",
    "Atteint le plafond": "Reaches ceiling",
    "Beau design": "Stylish design",
    "Bon rapport qualité/prix": "Good value for money",
    "Intérieur & extérieur": "Indoor & outdoor",
    "Sûr pour enfants/animaux": "Safe for kids/pets",
    "Mode auto / veille": "Auto / standby mode",
}


def translate_string(s):
    """Lookup translation, returns original if not found."""
    return T.get(s, s)


def translate_voc(path):
    with open(path, encoding='utf-8') as f:
        d = json.load(f)
    untranslated = []

    def tr(s):
        if not s or s not in T:
            if s and any(c in s for c in 'äöüßÄÖÜéèêëàâïîôöùûçÉÈÊËÀÂÏÎÔÖÙÛÇœŒæÆ'):
                untranslated.append(s)
            return T.get(s, s)
        return T[s]

    if d.get('cpSummary'): d['cpSummary'] = tr(d['cpSummary'])
    if d.get('csSummary'): d['csSummary'] = tr(d['csSummary'])
    for k in ('cpWho','cpWhen','cpWhere','cpWhat'):
        if k in d and d[k].get('labels'):
            d[k]['labels'] = [tr(lbl) for lbl in d[k]['labels']]
    for k in ('negativeTopics','positiveTopics'):
        for t in d.get(k, []):
            for f in ('label','reason'):
                if t.get(f): t[f] = tr(t[f])
            if t.get('bullets'): t['bullets'] = [tr(b) for b in t['bullets']]
    for k in ('negativeInsights','positiveInsights'):
        for t in d.get(k, []):
            for f in ('finding','implication'):
                if t.get(f): t[f] = tr(t[f])
    for k in ('usageScenarios','buyersMotivation','customerExpectations'):
        for t in d.get(k, []):
            for f in ('label','reason'):
                if t.get(f): t[f] = tr(t[f])
    for tf in d.get('themeFilters', []):
        if tf.get('label'): tf['label'] = tr(tf['label'])

    with open(path, 'w', encoding='utf-8') as f:
        json.dump(d, f, indent=2, ensure_ascii=False)
    return untranslated


for path in [
    'reviews/DE/Lure/voc.json',
    'reviews/DE/Electric/voc.json',
    'reviews/FR/Lure/voc.json',
    'reviews/FR/Electric/voc.json',
]:
    full = os.path.join(BASE, path.replace('/', os.sep))
    miss = translate_voc(full)
    print(f'{path}: translated -> {len(miss)} non-English string(s) still in source language')
    for m in miss[:5]:
        print(f'   ! still: {m[:100]}')
